// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: renderer.proto

package proto

import (
	project "github.com/input-output-hk/catalyst-forge/lib/schema/proto/generated/project"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RenderManifestsRequest contains the deployment bundle to render
type RenderManifeststRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bundle is the deployment bundle to render
	Bundle *project.ModuleBundle `protobuf:"bytes,1,opt,name=bundle,proto3" json:"bundle,omitempty"`
	// env_data contains optional environment data to merge with the bundle
	EnvData       []byte `protobuf:"bytes,2,opt,name=env_data,json=envData,proto3" json:"env_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderManifeststRequest) Reset() {
	*x = RenderManifeststRequest{}
	mi := &file_renderer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderManifeststRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderManifeststRequest) ProtoMessage() {}

func (x *RenderManifeststRequest) ProtoReflect() protoreflect.Message {
	mi := &file_renderer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderManifeststRequest.ProtoReflect.Descriptor instead.
func (*RenderManifeststRequest) Descriptor() ([]byte, []int) {
	return file_renderer_proto_rawDescGZIP(), []int{0}
}

func (x *RenderManifeststRequest) GetBundle() *project.ModuleBundle {
	if x != nil {
		return x.Bundle
	}
	return nil
}

func (x *RenderManifeststRequest) GetEnvData() []byte {
	if x != nil {
		return x.EnvData
	}
	return nil
}

// RenderManifestsResponse contains the rendered YAML manifests
type RenderManifestsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// manifests contains the rendered YAML manifests, keyed by module name
	Manifests map[string][]byte `protobuf:"bytes,1,rep,name=manifests,proto3" json:"manifests,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// bundle_data contains the raw bundle data that was processed
	BundleData []byte `protobuf:"bytes,2,opt,name=bundle_data,json=bundleData,proto3" json:"bundle_data,omitempty"`
	// error contains error message if rendering failed
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenderManifestsResponse) Reset() {
	*x = RenderManifestsResponse{}
	mi := &file_renderer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenderManifestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenderManifestsResponse) ProtoMessage() {}

func (x *RenderManifestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_renderer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenderManifestsResponse.ProtoReflect.Descriptor instead.
func (*RenderManifestsResponse) Descriptor() ([]byte, []int) {
	return file_renderer_proto_rawDescGZIP(), []int{1}
}

func (x *RenderManifestsResponse) GetManifests() map[string][]byte {
	if x != nil {
		return x.Manifests
	}
	return nil
}

func (x *RenderManifestsResponse) GetBundleData() []byte {
	if x != nil {
		return x.BundleData
	}
	return nil
}

func (x *RenderManifestsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// HealthCheckRequest is empty for health checks
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_renderer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_renderer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_renderer_proto_rawDescGZIP(), []int{2}
}

// HealthCheckResponse indicates service health
type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status indicates if the service is healthy
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// timestamp of the health check
	Timestamp     int64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_renderer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_renderer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_renderer_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_renderer_proto protoreflect.FileDescriptor

const file_renderer_proto_rawDesc = "" +
	"\n" +
	"\x0erenderer.proto\x12\brenderer\x1a\x18project/deployment.proto\"c\n" +
	"\x17RenderManifeststRequest\x12-\n" +
	"\x06bundle\x18\x01 \x01(\v2\x15.project.ModuleBundleR\x06bundle\x12\x19\n" +
	"\benv_data\x18\x02 \x01(\fR\aenvData\"\xde\x01\n" +
	"\x17RenderManifestsResponse\x12N\n" +
	"\tmanifests\x18\x01 \x03(\v20.renderer.RenderManifestsResponse.ManifestsEntryR\tmanifests\x12\x1f\n" +
	"\vbundle_data\x18\x02 \x01(\fR\n" +
	"bundleData\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x1a<\n" +
	"\x0eManifestsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"\x14\n" +
	"\x12HealthCheckRequest\"K\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp2\xb6\x01\n" +
	"\x0fRendererService\x12W\n" +
	"\x0fRenderManifests\x12!.renderer.RenderManifeststRequest\x1a!.renderer.RenderManifestsResponse\x12J\n" +
	"\vHealthCheck\x12\x1c.renderer.HealthCheckRequest\x1a\x1d.renderer.HealthCheckResponseBFZDgithub.com/input-output-hk/catalyst-forge/foundry/renderer/pkg/protob\x06proto3"

var (
	file_renderer_proto_rawDescOnce sync.Once
	file_renderer_proto_rawDescData []byte
)

func file_renderer_proto_rawDescGZIP() []byte {
	file_renderer_proto_rawDescOnce.Do(func() {
		file_renderer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_renderer_proto_rawDesc), len(file_renderer_proto_rawDesc)))
	})
	return file_renderer_proto_rawDescData
}

var file_renderer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_renderer_proto_goTypes = []any{
	(*RenderManifeststRequest)(nil), // 0: renderer.RenderManifeststRequest
	(*RenderManifestsResponse)(nil), // 1: renderer.RenderManifestsResponse
	(*HealthCheckRequest)(nil),      // 2: renderer.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 3: renderer.HealthCheckResponse
	nil,                             // 4: renderer.RenderManifestsResponse.ManifestsEntry
	(*project.ModuleBundle)(nil),    // 5: project.ModuleBundle
}
var file_renderer_proto_depIdxs = []int32{
	5, // 0: renderer.RenderManifeststRequest.bundle:type_name -> project.ModuleBundle
	4, // 1: renderer.RenderManifestsResponse.manifests:type_name -> renderer.RenderManifestsResponse.ManifestsEntry
	0, // 2: renderer.RendererService.RenderManifests:input_type -> renderer.RenderManifeststRequest
	2, // 3: renderer.RendererService.HealthCheck:input_type -> renderer.HealthCheckRequest
	1, // 4: renderer.RendererService.RenderManifests:output_type -> renderer.RenderManifestsResponse
	3, // 5: renderer.RendererService.HealthCheck:output_type -> renderer.HealthCheckResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_renderer_proto_init() }
func file_renderer_proto_init() {
	if File_renderer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_renderer_proto_rawDesc), len(file_renderer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_renderer_proto_goTypes,
		DependencyIndexes: file_renderer_proto_depIdxs,
		MessageInfos:      file_renderer_proto_msgTypes,
	}.Build()
	File_renderer_proto = out.File
	file_renderer_proto_goTypes = nil
	file_renderer_proto_depIdxs = nil
}
