name: Discovery
description: Discovers Earthfiles
inputs:
  filters:
    description: A newline separated list of filters to apply
    default: ""
  path:
    description: The path to search from
    default: "."
outputs:
  result:
    description: The result of the discovery

runs:
  using: node20
  main: dist/index.js
