apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-repo-gitea
  namespace: argocd
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: argocd-repo-gitea
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: "{{ .repo_ssh_url }}"
        sshPrivateKey: "{{ .ssh_private_key }}"
        known_hosts: "{{ .known_hosts }}"
  dataFrom:
    - extract:
        key: shared-services/git/gitea/bootstrap
