apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitea-db
  namespace: gitea
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: gitea-db
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        host: "{{ .host }}"
        port: "{{ .port }}"
        database: "{{ .database }}"
        dsn: "postgres://{{ .username }}:{{ .password }}@{{ .host }}:{{ .port }}/{{ .database }}?sslmode=disable"
  dataFrom:
    - extract:
        key: shared-services/db/gitea
