apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: hydra-dsn
  namespace: auth
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: hydra-dsn
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        dsn: "postgres://{{ .username }}:{{ .password }}@{{ .host }}:{{ .port }}/hydra?sslmode=disable"
  dataFrom:
    - extract:
        key: shared-services/db/hydra
