apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kratos-dsn
  namespace: auth
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: kratos-dsn
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        dsn: "postgres://{{ .username }}:{{ .password }}@{{ .host }}:{{ .port }}/kratos?sslmode=disable"
  dataFrom:
    - extract:
        key: shared-services/db/kratos
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kratos-oidc-google
  namespace: auth
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: kratos-oidc-google
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: client_id
      remoteRef:
        key: shared-services/auth/kratos/oidc/google
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: shared-services/auth/kratos/oidc/google
        property: client_secret
