apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: temporal-default-store
  namespace: temporal
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: temporal-default-store
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: shared-services/db/temporal
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: temporal-visibility-store
  namespace: temporal
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: temporal-visibility-store
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        password: "{{ .password }}"
  dataFrom:
    - extract:
        key: shared-services/db/temporal_visibility
