// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/input-output-hk/catalyst-forge/lib/foundry/client/jwks"
	"sync"
)

// Ensure, that JWKSClientInterfaceMock does implement jwks.JWKSClientInterface.
// If this is not the case, regenerate this file with moq.
var _ jwks.JWKSClientInterface = &JWKSClientInterfaceMock{}

// JWKSClientInterfaceMock is a mock implementation of jwks.JWKSClientInterface.
//
//	func TestSomethingThatUsesJWKSClientInterface(t *testing.T) {
//
//		// make and configure a mocked jwks.JWKSClientInterface
//		mockedJWKSClientInterface := &JWKSClientInterfaceMock{
//			GetFunc: func(ctx context.Context) ([]byte, error) {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedJWKSClientInterface in code that requires jwks.JWKSClientInterface
//		// and then make assertions.
//
//	}
type JWKSClientInterfaceMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *JWKSClientInterfaceMock) Get(ctx context.Context) ([]byte, error) {
	if mock.GetFunc == nil {
		panic("JWKSClientInterfaceMock.GetFunc: method is nil but JWKSClientInterface.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedJWKSClientInterface.GetCalls())
func (mock *JWKSClientInterfaceMock) GetCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}
