/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/.well-known/jwks.json': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get JWKS
		 * @description Returns the public JSON Web Key Set used to verify access tokens
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description JWKS */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/challenge': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Create a new authentication challenge
		 * @description Create a new challenge for user authentication using Ed25519 keys
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description Challenge creation request */
			requestBody: {
				content: {
					'application/json': components['schemas']['handlers.ChallengeRequest'];
				};
			};
			responses: {
				/** @description Challenge created successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['handlers.ChallengeResponse'];
					};
				};
				/** @description Invalid request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description User key not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/github': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List GHA authentication configurations
		 * @description Get all GitHub Actions authentication configurations
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of authentication configurations */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['handlers.GithubRepositoryAuthResponse'][];
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		put?: never;
		/**
		 * Create GHA authentication configuration
		 * @description Create a new GitHub Actions authentication configuration for a repository
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description GHA authentication configuration */
			requestBody: {
				content: {
					'application/json': components['schemas']['handlers.CreateAuthRequest'];
				};
			};
			responses: {
				/** @description Authentication configuration created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['handlers.GithubRepositoryAuthResponse'];
					};
				};
				/** @description Invalid request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/github/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get GHA authentication configuration by ID
		 * @description Get a specific GitHub Actions authentication configuration by its ID
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Authentication configuration ID */
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Authentication configuration */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['handlers.GithubRepositoryAuthResponse'];
					};
				};
				/** @description Invalid ID parameter */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Authentication configuration not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		/**
		 * Update GHA authentication configuration
		 * @description Update an existing GitHub Actions authentication configuration
		 */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Authentication configuration ID */
					id: number;
				};
				cookie?: never;
			};
			/** @description Updated GHA authentication configuration */
			requestBody: {
				content: {
					'application/json': components['schemas']['handlers.UpdateAuthRequest'];
				};
			};
			responses: {
				/** @description Authentication configuration updated */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['handlers.GithubRepositoryAuthResponse'];
					};
				};
				/** @description Invalid request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Authentication configuration not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		post?: never;
		/**
		 * Delete GHA authentication configuration
		 * @description Delete a GitHub Actions authentication configuration
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Authentication configuration ID */
					id: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Authentication configuration deleted */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Invalid ID parameter */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/github/login': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Validate GitHub Actions token
		 * @description Validate a GitHub Actions OIDC token and return a JWT token
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description Token validation request */
			requestBody: {
				content: {
					'application/json': components['schemas']['handlers.ValidateTokenRequest'];
				};
			};
			responses: {
				/** @description Token validated successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['handlers.ValidateTokenResponse'];
					};
				};
				/** @description Invalid request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Invalid token */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Repository not authorized */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/github/repository/{repository}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get GHA authentication configuration by repository
		 * @description Get a GitHub Actions authentication configuration by repository name
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Repository name */
					repository: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Authentication configuration */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['handlers.GithubRepositoryAuthResponse'];
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Authentication configuration not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/invites': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Create invite
		 * @description Create an invite for a user with one or more roles; optionally emails a verification link
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description Invite creation request */
			requestBody: {
				content: {
					'application/json': components['schemas']['handlers.CreateInviteRequest'];
				};
			};
			responses: {
				/** @description Created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['handlers.CreateInviteResponse'];
					};
				};
				/** @description Invalid request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/keys': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List all user keys
		 * @description Retrieve a list of all user keys
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of user keys */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['user.UserKey'][];
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		put?: never;
		/**
		 * Create a new user key
		 * @description Create a new Ed25519 key for a user
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description User key creation request */
			requestBody: {
				content: {
					'application/json': components['schemas']['user.CreateUserKeyRequest'];
				};
			};
			responses: {
				/** @description User key created successfully */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['user.UserKey'];
					};
				};
				/** @description Invalid request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description User key already exists */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/keys/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get a user key by ID
		 * @description Retrieve a user key by their ID
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description User Key ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description User key found */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['user.UserKey'];
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description User key not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		/**
		 * Update a user key
		 * @description Update an existing user key's information
		 */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description User Key ID */
					id: string;
				};
				cookie?: never;
			};
			/** @description User key update request */
			requestBody: {
				content: {
					'application/json': components['schemas']['user.UpdateUserKeyRequest'];
				};
			};
			responses: {
				/** @description User key updated successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['user.UserKey'];
					};
				};
				/** @description Invalid request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description User key not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		post?: never;
		/**
		 * Delete a user key
		 * @description Delete a user key by their ID
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description User Key ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description User key deleted successfully */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'*/*': {
							[key: string]: unknown;
						};
					};
				};
				/** @description User key not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'*/*': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'*/*': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/keys/{id}/revoke': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Revoke a user key
		 * @description Revoke a user key by setting its status to revoked
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description User Key ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description User key revoked successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'*/*': components['schemas']['user.UserKey'];
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'*/*': {
							[key: string]: unknown;
						};
					};
				};
				/** @description User key not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'*/*': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'*/*': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/keys/kid/{kid}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get a user key by kid
		 * @description Retrieve a user key by their kid (key ID)
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Key ID */
					kid: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description User key found */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['user.UserKey'];
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description User key not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/keys/register': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Register a new user key
		 * @description Register a new Ed25519 key for a user with inactive status
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description User key registration request */
			requestBody: {
				content: {
					'application/json': components['schemas']['user.RegisterUserKeyRequest'];
				};
			};
			responses: {
				/** @description User key registered successfully */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['user.UserKey'];
					};
				};
				/** @description Invalid request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description User not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description User key already exists */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/keys/user/{user_id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get user keys by user ID
		 * @description Retrieve all keys for a specific user
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description User ID */
					user_id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of user keys */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['user.UserKey'][];
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/keys/user/{user_id}/active': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get active user keys by user ID
		 * @description Get all active user keys for a specific user
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description User ID */
					user_id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of active user keys */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['user.UserKey'][];
					};
				};
				/** @description Invalid user ID */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/keys/user/{user_id}/inactive': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get inactive user keys by user ID
		 * @description Get all inactive user keys for a specific user
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description User ID */
					user_id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of inactive user keys */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['user.UserKey'][];
					};
				};
				/** @description Invalid user ID */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/login': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Authenticate user with challenge response
		 * @description Authenticate a user using their signed challenge response
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description Login request */
			requestBody: {
				content: {
					'application/json': components['schemas']['handlers.LoginRequest'];
				};
			};
			responses: {
				/** @description Authentication successful */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['handlers.LoginResponse'];
					};
				};
				/** @description Invalid request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Authentication failed */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Challenge or user not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/pending/keys': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get all inactive user keys
		 * @description Get all user keys with inactive status
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of inactive user keys */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['user.UserKey'][];
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/pending/users': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List pending users
		 * @description Get a list of all users with pending status
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of pending users */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['internal_api_handlers_user.User'][];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/role-users': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get all users for a role
		 * @description Retrieve all users assigned to a specific role
		 */
		get: {
			parameters: {
				query: {
					/** @description Role ID */
					role_id: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of role users */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['internal_api_handlers_user.UserRole'][];
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Role not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/roles': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List all roles
		 * @description Retrieve a list of all roles
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of roles */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['internal_api_handlers_user.Role'][];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		put?: never;
		/**
		 * Create a new role
		 * @description Create a new role with the provided information
		 */
		post: {
			parameters: {
				query?: {
					/** @description If true, ignore permissions and add all permissions */
					admin?: boolean;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description Role creation request */
			requestBody: {
				content: {
					'application/json': components['schemas']['user.CreateRoleRequest'];
				};
			};
			responses: {
				/** @description Role created successfully */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['internal_api_handlers_user.Role'];
					};
				};
				/** @description Invalid request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Role already exists */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/roles/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get a role by ID
		 * @description Retrieve a role by their ID
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Role ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Role found */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['internal_api_handlers_user.Role'];
					};
				};
				/** @description Role not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		/**
		 * Update a role
		 * @description Update an existing role's information
		 */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Role ID */
					id: string;
				};
				cookie?: never;
			};
			/** @description Role update request */
			requestBody: {
				content: {
					'application/json': components['schemas']['user.UpdateRoleRequest'];
				};
			};
			responses: {
				/** @description Role updated successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['internal_api_handlers_user.Role'];
					};
				};
				/** @description Invalid request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Role not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		post?: never;
		/**
		 * Delete a role
		 * @description Delete a role by their ID
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Role ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Role deleted successfully */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Role not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'*/*': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'*/*': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/roles/name/{name}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get a role by name
		 * @description Retrieve a role by their name
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Role name */
					name: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Role found */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['internal_api_handlers_user.Role'];
					};
				};
				/** @description Role not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/user-roles': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get all roles for a user
		 * @description Retrieve all roles assigned to a specific user
		 */
		get: {
			parameters: {
				query: {
					/** @description User ID */
					user_id: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of user roles */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['internal_api_handlers_user.UserRole'][];
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description User not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		put?: never;
		/**
		 * Assign a user to a role
		 * @description Assign a user to a specific role
		 */
		post: {
			parameters: {
				query: {
					/** @description User ID */
					user_id: string;
					/** @description Role ID */
					role_id: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description User assigned to role successfully */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['internal_api_handlers_user.UserRole'];
					};
				};
				/** @description Invalid request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description User or role not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description User already has this role */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		/**
		 * Remove a user from a role
		 * @description Remove a user from a specific role
		 */
		delete: {
			parameters: {
				query: {
					/** @description User ID */
					user_id: string;
					/** @description Role ID */
					role_id: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description User removed from role successfully */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'*/*': {
							[key: string]: unknown;
						};
					};
				};
				/** @description User or role not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'*/*': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'*/*': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/users': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List all users
		 * @description Get a list of all users in the system
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of users */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['internal_api_handlers_user.User'][];
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		put?: never;
		/**
		 * Create a new user
		 * @description Create a new user with the provided information
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description User creation request */
			requestBody: {
				content: {
					'application/json': components['schemas']['user.CreateUserRequest'];
				};
			};
			responses: {
				/** @description User created successfully */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['internal_api_handlers_user.User'];
					};
				};
				/** @description Invalid request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description User already exists */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/users/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get a user by ID
		 * @description Retrieve a user by their ID
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description User ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description User found */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['internal_api_handlers_user.User'];
					};
				};
				/** @description User not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		/**
		 * Update a user
		 * @description Update an existing user's information
		 */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description User ID */
					id: string;
				};
				cookie?: never;
			};
			/** @description User update request */
			requestBody: {
				content: {
					'application/json': components['schemas']['user.UpdateUserRequest'];
				};
			};
			responses: {
				/** @description User updated successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['internal_api_handlers_user.User'];
					};
				};
				/** @description Invalid request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description User not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		post?: never;
		/**
		 * Delete a user
		 * @description Delete a user by their ID
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description User ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description User deleted successfully */
				204: {
					headers: {
						[name: string]: unknown;
					};
					content?: never;
				};
				/** @description User not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'*/*': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'*/*': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/users/{id}/activate': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Activate a user
		 * @description Activate a user by setting their status to active
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description User ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description User activated successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'*/*': components['schemas']['internal_api_handlers_user.User'];
					};
				};
				/** @description User not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'*/*': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'*/*': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/users/{id}/deactivate': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Deactivate a user
		 * @description Deactivate a user by setting their status to inactive
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description User ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description User deactivated successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'*/*': components['schemas']['internal_api_handlers_user.User'];
					};
				};
				/** @description User not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'*/*': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'*/*': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/users/email/{email}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get a user by email
		 * @description Retrieve a user by their email address
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description User email */
					email: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description User found */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['internal_api_handlers_user.User'];
					};
				};
				/** @description User not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/users/register': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Register a new user
		 * @description Register a new user with pending status
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description User registration request */
			requestBody: {
				content: {
					'application/json': components['schemas']['user.RegisterUserRequest'];
				};
			};
			responses: {
				/** @description User registered successfully */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['internal_api_handlers_user.User'];
					};
				};
				/** @description Invalid request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description User already exists */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/ca/buildkit/server-certificates': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Sign a BuildKit server certificate
		 * @description Signs a server CSR
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description Server certificate signing request */
			requestBody: {
				content: {
					'application/json': components['schemas']['handlers.CertificateSigningRequest'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['handlers.CertificateSigningResponse'];
					};
				};
				/** @description Invalid request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Forbidden - insufficient permissions */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/certificates/root': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get root certificate
		 * @description Returns the Certificate Authority's root certificate
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description PEM-encoded root certificate */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'text/plain': string;
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'text/plain': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/certificates/sign': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Sign a certificate
		 * @description Signs a Certificate Signing Request (CSR)
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description Certificate signing request */
			requestBody: {
				content: {
					'application/json': components['schemas']['handlers.CertificateSigningRequest'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['handlers.CertificateSigningResponse'];
					};
				};
				/** @description Invalid request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Forbidden - insufficient permissions */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/device/approve': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Approve device session
		 * @description Approve a pending device session identified by user_code
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description Approval request */
			requestBody: {
				content: {
					'application/json': components['schemas']['handlers.DeviceApproveRequest'];
				};
			};
			responses: {
				/** @description approved */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Invalid request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/device/init': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Start device authorization
		 * @description Initialize a device authorization session and return device_code and user_code
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description Optional device metadata */
			requestBody?: {
				content: {
					'application/json': components['schemas']['handlers.DeviceInitRequest'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['handlers.DeviceInitResponse'];
					};
				};
				/** @description Server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/device/token': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Poll device token
		 * @description Poll the device authorization session for completion and receive tokens when approved
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description Device token request */
			requestBody: {
				content: {
					'application/json': components['schemas']['handlers.DeviceTokenRequest'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['handlers.DeviceTokenResponse'];
					};
				};
				/** @description Invalid request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description authorization_pending | expired_token | access_denied */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['handlers.DeviceTokenResponse'];
					};
				};
				/** @description slow_down */
				429: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['handlers.DeviceTokenResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/healthz': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Health check
		 * @description Check the health status of the API service
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Service is healthy */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Service is unhealthy */
				503: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/release': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Create a new release
		 * @description Create a new release with the specified source repository and project details
		 */
		post: {
			parameters: {
				query?: {
					/** @description Deploy the release immediately (true/false) */
					deploy?: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description Release creation request */
			requestBody: {
				content: {
					'application/json': components['schemas']['handlers.CreateReleaseRequest'];
				};
			};
			responses: {
				/** @description Release created successfully */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['models.Release'];
					};
				};
				/** @description Invalid request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/release/{id}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get a release by ID
		 * @description Retrieve a specific release by its ID
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Release ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Release details */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['models.Release'];
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Release not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		/**
		 * Update a release
		 * @description Update an existing release with new information
		 */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Release ID */
					id: string;
				};
				cookie?: never;
			};
			/** @description Release update request */
			requestBody: {
				content: {
					'application/json': components['schemas']['handlers.UpdateReleaseRequest'];
				};
			};
			responses: {
				/** @description Release updated successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['models.Release'];
					};
				};
				/** @description Invalid request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Release not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/release/{id}/aliases': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List release aliases
		 * @description Get all aliases for a specific release
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Release ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of aliases */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['models.ReleaseAlias'][];
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/release/{id}/deploy': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Create a deployment
		 * @description Create a new deployment for a release
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Release ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Deployment created successfully */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['models.ReleaseDeployment'];
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/release/{id}/deploy/{deployId}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get a deployment
		 * @description Get a specific deployment by its ID
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Release ID */
					id: string;
					/** @description Deployment ID */
					deployId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Deployment details */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['models.ReleaseDeployment'];
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Deployment not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		/**
		 * Update a deployment
		 * @description Update an existing deployment
		 */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Release ID */
					id: string;
					/** @description Deployment ID */
					deployId: string;
				};
				cookie?: never;
			};
			/** @description Deployment update request */
			requestBody: {
				content: {
					'application/json': components['schemas']['models.ReleaseDeployment'];
				};
			};
			responses: {
				/** @description Deployment updated successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['models.ReleaseDeployment'];
					};
				};
				/** @description Invalid request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/release/{id}/deploy/{deployId}/events': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get deployment events
		 * @description Get all events for a deployment
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Release ID */
					id: string;
					/** @description Deployment ID */
					deployId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of deployment events */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['models.DeploymentEvent'][];
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		put?: never;
		/**
		 * Add deployment event
		 * @description Add an event to a deployment
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Release ID */
					id: string;
					/** @description Deployment ID */
					deployId: string;
				};
				cookie?: never;
			};
			/** @description Event details */
			requestBody: {
				content: {
					'application/json': components['schemas']['handlers.AddEventRequest'];
				};
			};
			responses: {
				/** @description Deployment with updated events */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['models.ReleaseDeployment'];
					};
				};
				/** @description Invalid request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/release/{id}/deploy/latest': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get latest deployment
		 * @description Get the most recent deployment for a release
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Release ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Latest deployment */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['models.ReleaseDeployment'];
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description No deployments found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/release/{id}/deployments': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List deployments
		 * @description Get all deployments for a release
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Release ID */
					id: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of deployments */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['models.ReleaseDeployment'][];
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/release/alias/{name}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get release by alias
		 * @description Retrieve a release by its alias name
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Release alias name */
					name: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Release details */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['models.Release'];
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Release alias not found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		put?: never;
		/**
		 * Create a release alias
		 * @description Create an alias for a release
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Alias name */
					name: string;
				};
				cookie?: never;
			};
			/** @description Alias creation request */
			requestBody: {
				content: {
					'application/json': components['schemas']['handlers.CreateAliasRequest'];
				};
			};
			responses: {
				/** @description Alias created successfully */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Invalid request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		/**
		 * Delete a release alias
		 * @description Delete an alias for a release
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Alias name */
					name: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Alias deleted successfully */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/releases': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List releases
		 * @description Get all releases, optionally filtered by project
		 */
		get: {
			parameters: {
				query?: {
					/** @description Filter releases by project name */
					project?: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description List of releases */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['models.Release'][];
					};
				};
				/** @description Authentication required */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Internal server error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/verify': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Verify invite
		 * @description Verify an invite token and activate the user; assigns roles from the invite
		 */
		get: {
			parameters: {
				query: {
					/** @description Invite token */
					token: string;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description verified */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Missing token */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
				/** @description Invalid or expired */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': {
							[key: string]: unknown;
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		'handlers.AddEventRequest': {
			message: string;
			name: string;
		};
		'handlers.CertificateSigningRequest': {
			/**
			 * @description CommonName can override the CN in the CSR
			 * @example user.example.com
			 */
			common_name?: string;
			/**
			 * @description CSR is the PEM-encoded Certificate Signing Request
			 * @example -----BEGIN CERTIFICATE REQUEST-----
			 *     ...
			 */
			csr: string;
			/**
			 * @description SANs are additional Subject Alternative Names to include
			 *     These will be validated against user permissions. For client certs, use URI SANs.
			 * @example [
			 *       "example.com",
			 *       "*.example.com"
			 *     ]
			 */
			sans?: string[];
			/**
			 * @description TTL is the requested certificate lifetime
			 *     Will be capped by server policy
			 * @example 24h
			 */
			ttl?: string;
		};
		'handlers.CertificateSigningResponse': {
			/**
			 * @description Certificate is the PEM-encoded signed certificate
			 * @example -----BEGIN CERTIFICATE-----
			 *     ...
			 */
			certificate?: string;
			/** @description CertificateChain includes intermediate certificates if available */
			certificate_chain?: string[];
			/**
			 * @description Fingerprint is the SHA256 fingerprint of the certificate
			 * @example sha256:abcdef...
			 */
			fingerprint?: string;
			/**
			 * @description NotAfter is when the certificate expires
			 * @example 2024-01-02T00:00:00Z
			 */
			not_after?: string;
			/**
			 * @description NotBefore is when the certificate becomes valid
			 * @example 2024-01-01T00:00:00Z
			 */
			not_before?: string;
			/**
			 * @description SerialNumber is the certificate's serial number
			 * @example 123456789
			 */
			serial_number?: string;
		};
		'handlers.ChallengeRequest': {
			email: string;
			kid: string;
		};
		'handlers.ChallengeResponse': {
			token?: string;
		};
		'handlers.CreateAliasRequest': {
			release_id: string;
		};
		'handlers.CreateAuthRequest': Record<string, never>;
		'handlers.CreateInviteRequest': {
			email?: string;
			roles?: string[];
			/** @description e.g., "72h" */
			ttl?: string;
		};
		'handlers.CreateInviteResponse': {
			id?: number;
			token?: string;
		};
		'handlers.CreateReleaseRequest': {
			bundle: string;
			project: string;
			project_path: string;
			source_branch?: string;
			source_commit: string;
			source_repo: string;
		};
		'handlers.DeviceApproveRequest': {
			user_code?: string;
		};
		'handlers.DeviceInitRequest': {
			fingerprint?: string;
			name?: string;
			platform?: string;
		};
		'handlers.DeviceInitResponse': {
			device_code?: string;
			expires_in?: number;
			interval?: number;
			user_code?: string;
			verification_uri?: string;
		};
		'handlers.DeviceTokenRequest': {
			device_code?: string;
		};
		'handlers.DeviceTokenResponse': {
			access?: string;
			/** @description authorization_pending | slow_down | expired_token | access_denied */
			error?: string;
			refresh?: string;
		};
		'handlers.GithubRepositoryAuthResponse': {
			created_at?: string;
			created_by?: string;
			description?: string;
			enabled?: boolean;
			id?: number;
			permissions?: string[];
			repository?: string;
			updated_at?: string;
			updated_by?: string;
		};
		'handlers.LoginRequest': {
			signature?: string;
			token?: string;
		};
		'handlers.LoginResponse': {
			token?: string;
		};
		'handlers.UpdateAuthRequest': Record<string, never>;
		'handlers.UpdateReleaseRequest': {
			bundle?: string;
			project_path?: string;
			source_branch?: string;
			source_commit?: string;
			source_repo?: string;
		};
		'handlers.ValidateTokenRequest': {
			audience?: string;
			token: string;
		};
		'handlers.ValidateTokenResponse': {
			expires_at?: string;
			token?: string;
			user_id?: string;
		};
		/** @description Role represents a role in the system */
		'internal_api_handlers_user.Role': {
			/** @example 2023-01-01T00:00:00Z */
			created_at?: string;
			/** @example 1 */
			id?: number;
			/** @example admin */
			name?: string;
			/** @example [
			 *       "user:read",
			 *       "user:write"
			 *     ] */
			permissions?: string[];
			/** @example 2023-01-01T00:00:00Z */
			updated_at?: string;
		};
		/** @description User represents a user in the system */
		'internal_api_handlers_user.User': {
			/** @example 2023-01-01T00:00:00Z */
			created_at?: string;
			/** @example user@example.com */
			email?: string;
			/** @example 123 */
			id?: number;
			/** @example active */
			status?: string;
			/** @example 2023-01-01T00:00:00Z */
			updated_at?: string;
		};
		/** @description UserRole represents a many-to-many relationship between users and roles */
		'internal_api_handlers_user.UserRole': {
			/** @example 2023-01-01T00:00:00Z */
			created_at?: string;
			/** @example 1 */
			id?: number;
			role?: components['schemas']['internal_api_handlers_user.Role'];
			/** @example 456 */
			role_id?: number;
			/** @example 2023-01-01T00:00:00Z */
			updated_at?: string;
			user?: components['schemas']['internal_api_handlers_user.User'];
			/** @example 123 */
			user_id?: number;
		};
		'internal_models_user.User': {
			/** @description Timestamps */
			created_at?: string;
			email?: string;
			email_verified_at?: string;
			id?: number;
			status?: components['schemas']['user.UserStatus'];
			updated_at?: string;
			user_ver?: number;
		};
		'models.DeploymentEvent': {
			created_at?: string;
			deployment_id?: string;
			id?: number;
			message?: string;
			name?: string;
			timestamp?: string;
			updated_at?: string;
		};
		/** @enum {string} */
		'models.DeploymentStatus': 'pending' | 'running' | 'succeeded' | 'failed';
		'models.Release': {
			bundle?: string;
			created?: string;
			/** @description Timestamps */
			created_at?: string;
			/** @description Relationships */
			deployments?: components['schemas']['models.ReleaseDeployment'][];
			id?: string;
			project?: string;
			project_path?: string;
			source_branch?: string;
			source_commit?: string;
			source_repo?: string;
			updated_at?: string;
		};
		'models.ReleaseAlias': {
			created_at?: string;
			name?: string;
			/** @description Relationships */
			release?: components['schemas']['models.Release'];
			release_id?: string;
			updated_at?: string;
		};
		'models.ReleaseDeployment': {
			attempts?: number;
			/** @description Timestamps */
			created_at?: string;
			events?: components['schemas']['models.DeploymentEvent'][];
			id?: string;
			reason?: string;
			/** @description Relationships */
			release?: components['schemas']['models.Release'];
			release_id?: string;
			status?: components['schemas']['models.DeploymentStatus'];
			timestamp?: string;
			updated_at?: string;
		};
		'user.CreateRoleRequest': {
			name: string;
			permissions?: string[];
		};
		'user.CreateUserKeyRequest': {
			kid: string;
			pubkey_b64: string;
			status?: string;
			user_id: number;
		};
		'user.CreateUserRequest': {
			email: string;
			status?: string;
		};
		'user.RegisterUserKeyRequest': {
			email: string;
			kid: string;
			pubkey_b64: string;
		};
		'user.RegisterUserRequest': {
			email: string;
		};
		'user.UpdateRoleRequest': {
			name: string;
			permissions: string[];
		};
		'user.UpdateUserKeyRequest': {
			kid?: string;
			pubkey_b64?: string;
			status?: string;
			user_id?: number;
		};
		'user.UpdateUserRequest': {
			email: string;
			status?: string;
		};
		'user.UserKey': {
			/** @description Timestamps */
			created_at?: string;
			/** @description Device association (optional) */
			device_id?: number;
			id?: number;
			kid?: string;
			pubkey_b64?: string;
			status?: components['schemas']['user.UserKeyStatus'];
			updated_at?: string;
			/** @description Relationships */
			user?: components['schemas']['internal_models_user.User'];
			user_id?: number;
		};
		/** @enum {string} */
		'user.UserKeyStatus': 'active' | 'inactive' | 'revoked';
		/** @enum {string} */
		'user.UserStatus': 'pending' | 'active' | 'inactive';
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
