name: Install local forge CLI
description: Installs a local version of the forge CLI
inputs:
  earthly_token:
        description: Earthly token used to login to Earthly cloud for local build
        required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: echo "Building Forge CLI locally..."
    - name: Cache Earthly binary
      id: cache-earthly
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/earthly
        key: ${{ runner.os }}
    - name: Install Earthly
      if: steps.cache-earthly.outputs.cache-hit == false
      shell: bash
      run: |
        wget -q https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly
        chmod +x /usr/local/bin/earthly
        /usr/local/bin/earthly bootstrap
    - name: Login to Earthly Cloud
      if: steps.cache-binary.outputs.cache-hit == false
      shell: bash
      run: |
        earthly account login --token ${{ inputs.earthly_token }}
        earthly org select Catalyst
    - name: Cache binary
      id: cache-binary
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/forge
        key: ${{ runner.os }}-${{ github.sha }}
    - name: Build Forge CLI
      if: steps.cache-binary.outputs.cache-hit == false
      shell: bash
      run: |
        echo "::group::Forge CLI Earthly Build"
        earthly --sat ci --artifact ./cli+build/forge /usr/local/bin/forge
        echo "::endgroup::"