// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package common

// CIRetries contains the configuration for the retries of an Earthly target.
type CIRetries struct {
	// Attempts contains the number of attempts to retry the target.
	Attempts int64 `json:"attempts"`

	// Delay contains the delay between retries.
	Delay string `json:"delay"`

	// Filters filters retries based on the log lines from the Earthly run.
	Filters []string `json:"filters,omitempty"`
}

type Secret struct {
	// Maps contains mappings for Earthly secret names to JSON keys in the secret.
	// Mutually exclusive with Name.
	Maps map[string]string `json:"maps,omitempty"`

	// Name contains the name of the Earthly secret to use.
	// Mutually exclusive with Maps.
	Name string `json:"name,omitempty"`

	// Optional determines if the secret is optional.
	Optional bool `json:"optional,omitempty"`

	// Path contains the path to the secret.
	Path string `json:"path"`

	// Provider contains the provider to use for the secret.
	Provider string `json:"provider"`
}
