name: Publish
description: Publish container images
inputs:
  project:
    description: The path to the project
    required: true
  image:
    description: The full image name (name:tag) to publish
    required: true
  skip_branch_check:
    description: If true, will always publish images, even on pushes to the non-default branch
    required: false
    default: "false"
  target:
    description: The Earthly target that was run
    required: true

runs:
  using: node20
  main: dist/index.js
