VERSION 0.8

deps:
    FROM golang:1.24.2-bookworm

    WORKDIR /work

    RUN apt-get update && apt-get install -y file

    RUN mkdir -p /go/cache && mkdir -p /go/modcache
    ENV GOCACHE=/go/cache
    ENV GOMODCACHE=/go/modcache
    CACHE --persist --sharing shared /go

    RUN go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.3.1

    COPY go.mod go.sum ./
    RUN go mod download

src:
    FROM +deps

    CACHE --persist --sharing shared /go

    COPY --dir cmd internal .

    SAVE ARTIFACT . src

check:
    FROM +src

    RUN gofmt -l . | grep . && exit 1 || exit 0
    RUN go vet ./...
    RUN golangci-lint run

test:
    FROM +src

    RUN go test ./...

build:
    FROM +src

    ARG GOOS
    ARG GOARCH
    ARG version="0.0.0"

    ENV CGO_ENABLED=0
    RUN go build -ldflags="-extldflags=-static -X main.version=$version" -o bin/auth ./cmd/auth/main.go
    RUN file bin/auth

    SAVE ARTIFACT bin/auth auth

docker:
    FROM debian:latest
    WORKDIR /app

    ARG container="auth"
    ARG tag="latest"

    ARG TARGETOS
    ARG TARGETARCH
    ARG TARGETPLATFORM

    COPY \
        --platform=$TARGETPLATFORM \
        (+build/auth \
        --GOOS=$TARGETOS \
        --GOARCH=$TARGETARCH \
        --version=$version) auth

    ENTRYPOINT [ "/app/auth" ]
    SAVE IMAGE ${container}:${tag}