// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/input-output-hk/catalyst-forge/lib/foundry/client/github"
	"sync"
)

// Ensure, that GithubClientInterfaceMock does implement github.GithubClientInterface.
// If this is not the case, regenerate this file with moq.
var _ github.GithubClientInterface = &GithubClientInterfaceMock{}

// GithubClientInterfaceMock is a mock implementation of github.GithubClientInterface.
//
//	func TestSomethingThatUsesGithubClientInterface(t *testing.T) {
//
//		// make and configure a mocked github.GithubClientInterface
//		mockedGithubClientInterface := &GithubClientInterfaceMock{
//			CreateAuthFunc: func(ctx context.Context, req *github.CreateAuthRequest) (*github.GithubRepositoryAuth, error) {
//				panic("mock out the CreateAuth method")
//			},
//			DeleteAuthFunc: func(ctx context.Context, id uint) error {
//				panic("mock out the DeleteAuth method")
//			},
//			GetAuthFunc: func(ctx context.Context, id uint) (*github.GithubRepositoryAuth, error) {
//				panic("mock out the GetAuth method")
//			},
//			GetAuthByRepositoryFunc: func(ctx context.Context, repository string) (*github.GithubRepositoryAuth, error) {
//				panic("mock out the GetAuthByRepository method")
//			},
//			ListAuthsFunc: func(ctx context.Context) ([]github.GithubRepositoryAuth, error) {
//				panic("mock out the ListAuths method")
//			},
//			UpdateAuthFunc: func(ctx context.Context, id uint, req *github.UpdateAuthRequest) (*github.GithubRepositoryAuth, error) {
//				panic("mock out the UpdateAuth method")
//			},
//			ValidateTokenFunc: func(ctx context.Context, req *github.ValidateTokenRequest) (*github.ValidateTokenResponse, error) {
//				panic("mock out the ValidateToken method")
//			},
//		}
//
//		// use mockedGithubClientInterface in code that requires github.GithubClientInterface
//		// and then make assertions.
//
//	}
type GithubClientInterfaceMock struct {
	// CreateAuthFunc mocks the CreateAuth method.
	CreateAuthFunc func(ctx context.Context, req *github.CreateAuthRequest) (*github.GithubRepositoryAuth, error)

	// DeleteAuthFunc mocks the DeleteAuth method.
	DeleteAuthFunc func(ctx context.Context, id uint) error

	// GetAuthFunc mocks the GetAuth method.
	GetAuthFunc func(ctx context.Context, id uint) (*github.GithubRepositoryAuth, error)

	// GetAuthByRepositoryFunc mocks the GetAuthByRepository method.
	GetAuthByRepositoryFunc func(ctx context.Context, repository string) (*github.GithubRepositoryAuth, error)

	// ListAuthsFunc mocks the ListAuths method.
	ListAuthsFunc func(ctx context.Context) ([]github.GithubRepositoryAuth, error)

	// UpdateAuthFunc mocks the UpdateAuth method.
	UpdateAuthFunc func(ctx context.Context, id uint, req *github.UpdateAuthRequest) (*github.GithubRepositoryAuth, error)

	// ValidateTokenFunc mocks the ValidateToken method.
	ValidateTokenFunc func(ctx context.Context, req *github.ValidateTokenRequest) (*github.ValidateTokenResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateAuth holds details about calls to the CreateAuth method.
		CreateAuth []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *github.CreateAuthRequest
		}
		// DeleteAuth holds details about calls to the DeleteAuth method.
		DeleteAuth []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uint
		}
		// GetAuth holds details about calls to the GetAuth method.
		GetAuth []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uint
		}
		// GetAuthByRepository holds details about calls to the GetAuthByRepository method.
		GetAuthByRepository []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Repository is the repository argument value.
			Repository string
		}
		// ListAuths holds details about calls to the ListAuths method.
		ListAuths []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// UpdateAuth holds details about calls to the UpdateAuth method.
		UpdateAuth []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID uint
			// Req is the req argument value.
			Req *github.UpdateAuthRequest
		}
		// ValidateToken holds details about calls to the ValidateToken method.
		ValidateToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *github.ValidateTokenRequest
		}
	}
	lockCreateAuth          sync.RWMutex
	lockDeleteAuth          sync.RWMutex
	lockGetAuth             sync.RWMutex
	lockGetAuthByRepository sync.RWMutex
	lockListAuths           sync.RWMutex
	lockUpdateAuth          sync.RWMutex
	lockValidateToken       sync.RWMutex
}

// CreateAuth calls CreateAuthFunc.
func (mock *GithubClientInterfaceMock) CreateAuth(ctx context.Context, req *github.CreateAuthRequest) (*github.GithubRepositoryAuth, error) {
	if mock.CreateAuthFunc == nil {
		panic("GithubClientInterfaceMock.CreateAuthFunc: method is nil but GithubClientInterface.CreateAuth was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *github.CreateAuthRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockCreateAuth.Lock()
	mock.calls.CreateAuth = append(mock.calls.CreateAuth, callInfo)
	mock.lockCreateAuth.Unlock()
	return mock.CreateAuthFunc(ctx, req)
}

// CreateAuthCalls gets all the calls that were made to CreateAuth.
// Check the length with:
//
//	len(mockedGithubClientInterface.CreateAuthCalls())
func (mock *GithubClientInterfaceMock) CreateAuthCalls() []struct {
	Ctx context.Context
	Req *github.CreateAuthRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *github.CreateAuthRequest
	}
	mock.lockCreateAuth.RLock()
	calls = mock.calls.CreateAuth
	mock.lockCreateAuth.RUnlock()
	return calls
}

// DeleteAuth calls DeleteAuthFunc.
func (mock *GithubClientInterfaceMock) DeleteAuth(ctx context.Context, id uint) error {
	if mock.DeleteAuthFunc == nil {
		panic("GithubClientInterfaceMock.DeleteAuthFunc: method is nil but GithubClientInterface.DeleteAuth was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uint
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteAuth.Lock()
	mock.calls.DeleteAuth = append(mock.calls.DeleteAuth, callInfo)
	mock.lockDeleteAuth.Unlock()
	return mock.DeleteAuthFunc(ctx, id)
}

// DeleteAuthCalls gets all the calls that were made to DeleteAuth.
// Check the length with:
//
//	len(mockedGithubClientInterface.DeleteAuthCalls())
func (mock *GithubClientInterfaceMock) DeleteAuthCalls() []struct {
	Ctx context.Context
	ID  uint
} {
	var calls []struct {
		Ctx context.Context
		ID  uint
	}
	mock.lockDeleteAuth.RLock()
	calls = mock.calls.DeleteAuth
	mock.lockDeleteAuth.RUnlock()
	return calls
}

// GetAuth calls GetAuthFunc.
func (mock *GithubClientInterfaceMock) GetAuth(ctx context.Context, id uint) (*github.GithubRepositoryAuth, error) {
	if mock.GetAuthFunc == nil {
		panic("GithubClientInterfaceMock.GetAuthFunc: method is nil but GithubClientInterface.GetAuth was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uint
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetAuth.Lock()
	mock.calls.GetAuth = append(mock.calls.GetAuth, callInfo)
	mock.lockGetAuth.Unlock()
	return mock.GetAuthFunc(ctx, id)
}

// GetAuthCalls gets all the calls that were made to GetAuth.
// Check the length with:
//
//	len(mockedGithubClientInterface.GetAuthCalls())
func (mock *GithubClientInterfaceMock) GetAuthCalls() []struct {
	Ctx context.Context
	ID  uint
} {
	var calls []struct {
		Ctx context.Context
		ID  uint
	}
	mock.lockGetAuth.RLock()
	calls = mock.calls.GetAuth
	mock.lockGetAuth.RUnlock()
	return calls
}

// GetAuthByRepository calls GetAuthByRepositoryFunc.
func (mock *GithubClientInterfaceMock) GetAuthByRepository(ctx context.Context, repository string) (*github.GithubRepositoryAuth, error) {
	if mock.GetAuthByRepositoryFunc == nil {
		panic("GithubClientInterfaceMock.GetAuthByRepositoryFunc: method is nil but GithubClientInterface.GetAuthByRepository was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Repository string
	}{
		Ctx:        ctx,
		Repository: repository,
	}
	mock.lockGetAuthByRepository.Lock()
	mock.calls.GetAuthByRepository = append(mock.calls.GetAuthByRepository, callInfo)
	mock.lockGetAuthByRepository.Unlock()
	return mock.GetAuthByRepositoryFunc(ctx, repository)
}

// GetAuthByRepositoryCalls gets all the calls that were made to GetAuthByRepository.
// Check the length with:
//
//	len(mockedGithubClientInterface.GetAuthByRepositoryCalls())
func (mock *GithubClientInterfaceMock) GetAuthByRepositoryCalls() []struct {
	Ctx        context.Context
	Repository string
} {
	var calls []struct {
		Ctx        context.Context
		Repository string
	}
	mock.lockGetAuthByRepository.RLock()
	calls = mock.calls.GetAuthByRepository
	mock.lockGetAuthByRepository.RUnlock()
	return calls
}

// ListAuths calls ListAuthsFunc.
func (mock *GithubClientInterfaceMock) ListAuths(ctx context.Context) ([]github.GithubRepositoryAuth, error) {
	if mock.ListAuthsFunc == nil {
		panic("GithubClientInterfaceMock.ListAuthsFunc: method is nil but GithubClientInterface.ListAuths was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListAuths.Lock()
	mock.calls.ListAuths = append(mock.calls.ListAuths, callInfo)
	mock.lockListAuths.Unlock()
	return mock.ListAuthsFunc(ctx)
}

// ListAuthsCalls gets all the calls that were made to ListAuths.
// Check the length with:
//
//	len(mockedGithubClientInterface.ListAuthsCalls())
func (mock *GithubClientInterfaceMock) ListAuthsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListAuths.RLock()
	calls = mock.calls.ListAuths
	mock.lockListAuths.RUnlock()
	return calls
}

// UpdateAuth calls UpdateAuthFunc.
func (mock *GithubClientInterfaceMock) UpdateAuth(ctx context.Context, id uint, req *github.UpdateAuthRequest) (*github.GithubRepositoryAuth, error) {
	if mock.UpdateAuthFunc == nil {
		panic("GithubClientInterfaceMock.UpdateAuthFunc: method is nil but GithubClientInterface.UpdateAuth was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  uint
		Req *github.UpdateAuthRequest
	}{
		Ctx: ctx,
		ID:  id,
		Req: req,
	}
	mock.lockUpdateAuth.Lock()
	mock.calls.UpdateAuth = append(mock.calls.UpdateAuth, callInfo)
	mock.lockUpdateAuth.Unlock()
	return mock.UpdateAuthFunc(ctx, id, req)
}

// UpdateAuthCalls gets all the calls that were made to UpdateAuth.
// Check the length with:
//
//	len(mockedGithubClientInterface.UpdateAuthCalls())
func (mock *GithubClientInterfaceMock) UpdateAuthCalls() []struct {
	Ctx context.Context
	ID  uint
	Req *github.UpdateAuthRequest
} {
	var calls []struct {
		Ctx context.Context
		ID  uint
		Req *github.UpdateAuthRequest
	}
	mock.lockUpdateAuth.RLock()
	calls = mock.calls.UpdateAuth
	mock.lockUpdateAuth.RUnlock()
	return calls
}

// ValidateToken calls ValidateTokenFunc.
func (mock *GithubClientInterfaceMock) ValidateToken(ctx context.Context, req *github.ValidateTokenRequest) (*github.ValidateTokenResponse, error) {
	if mock.ValidateTokenFunc == nil {
		panic("GithubClientInterfaceMock.ValidateTokenFunc: method is nil but GithubClientInterface.ValidateToken was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *github.ValidateTokenRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockValidateToken.Lock()
	mock.calls.ValidateToken = append(mock.calls.ValidateToken, callInfo)
	mock.lockValidateToken.Unlock()
	return mock.ValidateTokenFunc(ctx, req)
}

// ValidateTokenCalls gets all the calls that were made to ValidateToken.
// Check the length with:
//
//	len(mockedGithubClientInterface.ValidateTokenCalls())
func (mock *GithubClientInterfaceMock) ValidateTokenCalls() []struct {
	Ctx context.Context
	Req *github.ValidateTokenRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *github.ValidateTokenRequest
	}
	mock.lockValidateToken.RLock()
	calls = mock.calls.ValidateToken
	mock.lockValidateToken.RUnlock()
	return calls
}
