VERSION 0.8

timoni:
    FROM golang:1.23.0

    ARG TIMONI_VERSION=v0.17.0

    WORKDIR /work

    RUN go install github.com/stefanprodan/timoni/cmd/timoni@${TIMONI_VERSION}
    SAVE ARTIFACT /go/bin/timoni timoni

docker:
    FROM debian:bookworm-slim

    ARG container="forge-argocd"
    ARG tag="latest"

    ARG TARGETOS
    ARG TARGETARCH
    ARG USERPLATFORM

    RUN apt-get update && apt-get install -y ca-certificates amazon-ecr-credential-helper
    RUN useradd -m -u 999 argocd

    USER argocd
    WORKDIR /home/argocd

    COPY +timoni/timoni /usr/local/bin/timoni
    COPY \
        --platform=$USERPLATFORM \
        (../../cli+build/forge \
        --GOOS=$TARGETOS \
        --GOARCH=$TARGETARCH \
        --version="argocd") /usr/local/bin/forge

    RUN mkdir -p cmp-server/config
    COPY plugin.yml cmp-server/config/plugin.yaml

    COPY init.sh /home/argocd/init.sh
    RUN chmod +x /home/argocd/init.sh

    ENTRYPOINT [ "/var/run/argocd/argocd-cmp-server" ]
    SAVE IMAGE ${container}:${tag}
