apiVersion: argoproj.io/v1alpha1
kind: ConfigManagementPlugin
metadata:
  name: forge-argocd
spec:
  version: v1.0.0
  generate:
    command: [/usr/local/bin/forge]
    args: ["deploy", "template", "."]
  discover:
    fileName: "./blueprint.cue"