VERSION 0.8

deps:
    FROM golang:1.24.5-bookworm

    WORKDIR /work

    RUN mkdir -p /go/cache && mkdir -p /go/modcache
    ENV GOCACHE=/go/cache
    ENV GOMODCACHE=/go/modcache
    CACHE --persist --sharing shared /go

    COPY ../external/helm+src/src /external/helm
    COPY ../external/kcl+src/src /external/kcl
    COPY ../oci+src/src /oci
    COPY ../project+src/src /project
    COPY ../providers+src/src /providers
    COPY ../schema+src/src /schema
    COPY ../tools+src/src /tools

    COPY go.mod go.sum .
    RUN go mod download

src:
    FROM +deps

    CACHE --persist --sharing shared /go

    COPY . .

    RUN go generate ./...

    SAVE ARTIFACT . src

check:
    FROM +src

    RUN gofmt -l . | grep . && exit 1 || exit 0
    RUN go vet ./...

test:
    FROM +src

    RUN go test ./...