apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-oidc
  namespace: mock-oidc
  labels:
    app: mock-oidc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-oidc
  template:
    metadata:
      labels:
        app: mock-oidc
    spec:
      containers:
        - name: mock-oauth2-server
          image: ghcr.io/navikt/mock-oauth2-server:2.1.7
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: INTERACTIVE_LOGIN
              value: "true"
            - name: TOKEN_ENDPOINT_AUTH_METHOD
              value: "client_secret_basic"
            - name: JSON_CONFIG
              value: |
                {
                  "interactiveLogin": true,
                  "httpServer": {"type": "MockWebServerWrapper"}
                }
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
