apiVersion: v1
kind: Service
metadata:
  name: mock-oidc
  namespace: mock-oidc
  labels:
    app: mock-oidc
spec:
  selector:
    app: mock-oidc
  ports:
    - name: http
      port: 80
      targetPort: 8080
