apiVersion: v1
kind: Service
metadata:
  name: earthly-buildkitd
  namespace: registry
spec:
  selector:
    app: earthly-buildkitd
  ports:
    - name: grpc
      port: 8372
      targetPort: 8372
  type: ClusterIP
