// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/input-output-hk/catalyst-forge/lib/tools/walker"
	"sync"
)

// Ensure, that WalkerMock does implement walker.Walker.
// If this is not the case, regenerate this file with moq.
var _ walker.Walker = &WalkerMock{}

// WalkerMock is a mock implementation of walker.Walker.
//
//	func TestSomethingThatUsesWalker(t *testing.T) {
//
//		// make and configure a mocked walker.Walker
//		mockedWalker := &WalkerMock{
//			WalkFunc: func(rootPath string, callback walker.WalkerCallback) error {
//				panic("mock out the Walk method")
//			},
//		}
//
//		// use mockedWalker in code that requires walker.Walker
//		// and then make assertions.
//
//	}
type WalkerMock struct {
	// WalkFunc mocks the Walk method.
	WalkFunc func(rootPath string, callback walker.WalkerCallback) error

	// calls tracks calls to the methods.
	calls struct {
		// Walk holds details about calls to the Walk method.
		Walk []struct {
			// RootPath is the rootPath argument value.
			RootPath string
			// Callback is the callback argument value.
			Callback walker.WalkerCallback
		}
	}
	lockWalk sync.RWMutex
}

// Walk calls WalkFunc.
func (mock *WalkerMock) Walk(rootPath string, callback walker.WalkerCallback) error {
	if mock.WalkFunc == nil {
		panic("WalkerMock.WalkFunc: method is nil but Walker.Walk was just called")
	}
	callInfo := struct {
		RootPath string
		Callback walker.WalkerCallback
	}{
		RootPath: rootPath,
		Callback: callback,
	}
	mock.lockWalk.Lock()
	mock.calls.Walk = append(mock.calls.Walk, callInfo)
	mock.lockWalk.Unlock()
	return mock.WalkFunc(rootPath, callback)
}

// WalkCalls gets all the calls that were made to Walk.
// Check the length with:
//
//	len(mockedWalker.WalkCalls())
func (mock *WalkerMock) WalkCalls() []struct {
	RootPath string
	Callback walker.WalkerCallback
} {
	var calls []struct {
		RootPath string
		Callback walker.WalkerCallback
	}
	mock.lockWalk.RLock()
	calls = mock.calls.Walk
	mock.lockWalk.RUnlock()
	return calls
}
