name: Release
description: Create a new GitHub release and upload generated artifacts
inputs:
  github_token:
    description: The token to use for creating a new release
    required: false
    default: ${{ github.token }}
  native_platform:
    description: The native platform that this action is being run in
    required: true
  project:
    description: The path to the project
    required: true
  path:
    description: The path to generated artifacts
    required: true
  target:
    description: The Earthly target that was run
    required: true

runs:
  using: node20
  main: dist/index.js
