// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package injector

import (
	"sync"
)

// Ensure, that EnvGetterMock does implement EnvGetter.
// If this is not the case, regenerate this file with moq.
var _ EnvGetter = &EnvGetterMock{}

// EnvGetterMock is a mock implementation of EnvGetter.
//
//	func TestSomethingThatUsesEnvGetter(t *testing.T) {
//
//		// make and configure a mocked EnvGetter
//		mockedEnvGetter := &EnvGetterMock{
//			GetFunc: func(key string) (string, bool) {
//				panic("mock out the Get method")
//			},
//		}
//
//		// use mockedEnvGetter in code that requires EnvGetter
//		// and then make assertions.
//
//	}
type EnvGetterMock struct {
	// GetFunc mocks the Get method.
	GetFunc func(key string) (string, bool)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
			// Key is the key argument value.
			Key string
		}
	}
	lockGet sync.RWMutex
}

// Get calls GetFunc.
func (mock *EnvGetterMock) Get(key string) (string, bool) {
	if mock.GetFunc == nil {
		panic("EnvGetterMock.GetFunc: method is nil but EnvGetter.Get was just called")
	}
	callInfo := struct {
		Key string
	}{
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedEnvGetter.GetCalls())
func (mock *EnvGetterMock) GetCalls() []struct {
	Key string
} {
	var calls []struct {
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}
