name: Setup CI
description: Sets up the CI with the configured providers
runs:
  using: composite
  steps:
    - name: Dump blueprint
      id: blueprint
      uses: input-output-hk/catalyst-forge/forge/actions/blueprint@adds-install-action
      with:
        path: .
    - name: Show
      shell: bash
      run: echo '${{ steps.blueprint.outputs.json }}'