name: Setup CI
description: Sets up the CI with the configured providers
inputs:
  version:
    description: The version of Catalyst Forge actions to use
    default: adds-install-action
runs:
  using: composite
  steps:
    - name: Dump blueprint
      id: blueprint
      uses: input-output-hk/catalyst-forge/forge/actions/blueprint@${{ inputs.version }}
      with:
        path: .
    - name: Show
      shell: bash
      run: echo '${{ steps.blueprint.outputs.json }}'