name: Setup CI
description: Sets up the CI with the configured providers
inputs:
  earthly_version:
    description: The version of Earthly to install
    default: latest
  forge_version:
    description: The version of the forge CLI to install (use 'local' for testing)
    default: latest
runs:
  using: composite
  steps:
    - name: Install Earthly
      uses: earthly/actions-setup@v1
      if: inputs.forge_version == 'local'
      with:
        version: ${{ inputs.earthly_version }}
    - name: Cache Forge CLI binary
      if: inputs.forge_version == 'local'
      id: cache-forge
      uses: actions/cache@v3
      with:
        path: /usr/local/bin/forge
        key: ${{ runner.os }}-forge-${{ hashFiles('forge/cli/**') }}
        restore-keys: |
          ${{ runner.os }}-forge-
    - name: Build Forge CLI
      if: steps.cache-forge.outputs.cache-hit != 'true' && inputs.forge_version == 'local'
      shell: bash
      run: |
          earthly --artifact ./forge/cli+build/forge /usr/local/bin/forge
    - name: Check version
      shell: bash
      run: forge version