log:
  level: info

serve:
  public:
    host: 0.0.0.0
    port: 4433
    # Externally visible base URL (via Caddy path-prefix passthrough)
    base_url: https://auth.projectcatalyst.dev/.ory/kratos/public
  admin:
    host: 0.0.0.0
    port: 4434

secrets:
  default:
    - "d835e3a5c00db4f349abfca116085fbc"
  cookie:
    - "74059701e15cc511a3d3ecdde4d033b7"
  cipher:
    - "8812e4c5719b1cd8e50578735e263311"

selfservice:
  default_browser_return_url: https://forge.projectcatalyst.dev/
  allowed_return_urls:
    - https://forge.projectcatalyst.dev/*
  flows:
    settings:
      ui_url: https://forge.projectcatalyst.dev//profile
    login:
      ui_url: https://forge.projectcatalyst.dev/welcome
    error:
      ui_url: https://forge.projectcatalyst.dev/auth/error
    registration:
      ui_url: https://forge.projectcatalyst.dev/welcome
      after:
        oidc:
          hooks:
            - hook: session
  methods:
    passkey:
      enabled: true
      config:
        rp:
          display_name: Catalyst Forge
          id: forge.projectcatalyst.dev
          origins:
            - https://forge.projectcatalyst.dev/
    oidc:
      enabled: true
      config:
        providers:
          - id: google
            provider: google
            client_id: ID
            client_secret: SECRET
            issuer_url: https://accounts.google.com
            mapper_url: file:///etc/kratos/google.mapper.jsonnet
            scope:
              - openid
              - email
              - profile

session:
  cookie:
    domain: projectcatalyst.dev
    same_site: Lax
    persistent: true
    path: /

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/kratos/identity.schema.json
