VERSION 0.8

deps:
    FROM golang:1.23.0-alpine3.19

    WORKDIR /work

    RUN apk add git file

    RUN mkdir -p /go/cache && mkdir -p /go/modcache
    ENV GOCACHE=/go/cache
    ENV GOMODCACHE=/go/modcache
    CACHE --persist --sharing shared /go

    COPY ../lib/project+src/src /lib/project
    COPY ../lib/tools+src/src /lib/tools

    COPY go.mod go.sum .
    RUN go mod download

src:
    FROM +deps

    CACHE --persist --sharing shared /go

    COPY . .
    RUN go generate ./...

check:
    FROM +src

    RUN gofmt -l . | grep . && exit 1 || exit 0
    RUN go vet ./...

build:
    FROM +src

    ARG GOOS
    ARG GOARCH
    ARG version="0.0.0"

    ENV CGO_ENABLED=0
    RUN go build -ldflags="-extldflags=-static -X main.version=$version" -o bin/gh-job-checker main.go
    RUN file bin/gh-job-checker

    SAVE ARTIFACT bin/gh-job-checker gh-job-checker

test:
    FROM +build

    RUN go test ./...

github:
    FROM scratch

    ARG version="dev"

    ARG TARGETOS
    ARG TARGETARCH
    ARG USERPLATFORM

    COPY \
        --platform=$USERPLATFORM \
        (+build/gh-job-checker \
        --GOOS=$TARGETOS \
        --GOARCH=$TARGETARCH \
        --version=$version) bin/gh-job-checker

    SAVE ARTIFACT bin/gh-job-checker gh-job-checker
