name: Run
description: Execute Earthfiles
inputs:
  args:
    description: The arguments to pass
    required: false
    default: ""
  command:
    description: The command to run
    required: true
  local:
    description: Forces local mode
    required: false
    default: "false"
  target_args:
    description: Extra arguments to pass to the target (if command is "run")
    required: false
    default: ""
  verbosity:
    description: The verbosity level to use
    required: false
    default: "info"
outputs:
  result:
    description: The result of running the command

runs:
  using: node20
  main: dist/index.js
