global:
  buildkit_host: tcp://buildkit.projectcatalyst.dev:8372
  tlsca: /Users/josh/work/catalyst-forge/playgroundv2/.certs/rootCA.pem
  tlscert: /Users/josh/work/catalyst-forge/playgroundv2/.certs/earthly-client.pem
  tlskey: /Users/josh/work/catalyst-forge/playgroundv2/.certs/earthly-client-key.pem
