// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package providers

import (
	"context"
	"github.com/aws/aws-sdk-go-v2/service/secretsmanager"
	"sync"
)

// Ensure, that SecretsManagerClientMock does implement SecretsManagerClient.
// If this is not the case, regenerate this file with moq.
var _ SecretsManagerClient = &SecretsManagerClientMock{}

// SecretsManagerClientMock is a mock implementation of SecretsManagerClient.
//
//	func TestSomethingThatUsesSecretsManagerClient(t *testing.T) {
//
//		// make and configure a mocked SecretsManagerClient
//		mockedSecretsManagerClient := &SecretsManagerClientMock{
//			CreateSecretFunc: func(ctx context.Context, params *secretsmanager.CreateSecretInput, optFns ...func(*secretsmanager.Options)) (*secretsmanager.CreateSecretOutput, error) {
//				panic("mock out the CreateSecret method")
//			},
//			GetSecretValueFunc: func(ctx context.Context, params *secretsmanager.GetSecretValueInput, optFns ...func(*secretsmanager.Options)) (*secretsmanager.GetSecretValueOutput, error) {
//				panic("mock out the GetSecretValue method")
//			},
//			PutSecretValueFunc: func(ctx context.Context, params *secretsmanager.PutSecretValueInput, optFns ...func(*secretsmanager.Options)) (*secretsmanager.PutSecretValueOutput, error) {
//				panic("mock out the PutSecretValue method")
//			},
//		}
//
//		// use mockedSecretsManagerClient in code that requires SecretsManagerClient
//		// and then make assertions.
//
//	}
type SecretsManagerClientMock struct {
	// CreateSecretFunc mocks the CreateSecret method.
	CreateSecretFunc func(ctx context.Context, params *secretsmanager.CreateSecretInput, optFns ...func(*secretsmanager.Options)) (*secretsmanager.CreateSecretOutput, error)

	// GetSecretValueFunc mocks the GetSecretValue method.
	GetSecretValueFunc func(ctx context.Context, params *secretsmanager.GetSecretValueInput, optFns ...func(*secretsmanager.Options)) (*secretsmanager.GetSecretValueOutput, error)

	// PutSecretValueFunc mocks the PutSecretValue method.
	PutSecretValueFunc func(ctx context.Context, params *secretsmanager.PutSecretValueInput, optFns ...func(*secretsmanager.Options)) (*secretsmanager.PutSecretValueOutput, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateSecret holds details about calls to the CreateSecret method.
		CreateSecret []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params *secretsmanager.CreateSecretInput
			// OptFns is the optFns argument value.
			OptFns []func(*secretsmanager.Options)
		}
		// GetSecretValue holds details about calls to the GetSecretValue method.
		GetSecretValue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params *secretsmanager.GetSecretValueInput
			// OptFns is the optFns argument value.
			OptFns []func(*secretsmanager.Options)
		}
		// PutSecretValue holds details about calls to the PutSecretValue method.
		PutSecretValue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params *secretsmanager.PutSecretValueInput
			// OptFns is the optFns argument value.
			OptFns []func(*secretsmanager.Options)
		}
	}
	lockCreateSecret   sync.RWMutex
	lockGetSecretValue sync.RWMutex
	lockPutSecretValue sync.RWMutex
}

// CreateSecret calls CreateSecretFunc.
func (mock *SecretsManagerClientMock) CreateSecret(ctx context.Context, params *secretsmanager.CreateSecretInput, optFns ...func(*secretsmanager.Options)) (*secretsmanager.CreateSecretOutput, error) {
	if mock.CreateSecretFunc == nil {
		panic("SecretsManagerClientMock.CreateSecretFunc: method is nil but SecretsManagerClient.CreateSecret was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params *secretsmanager.CreateSecretInput
		OptFns []func(*secretsmanager.Options)
	}{
		Ctx:    ctx,
		Params: params,
		OptFns: optFns,
	}
	mock.lockCreateSecret.Lock()
	mock.calls.CreateSecret = append(mock.calls.CreateSecret, callInfo)
	mock.lockCreateSecret.Unlock()
	return mock.CreateSecretFunc(ctx, params, optFns...)
}

// CreateSecretCalls gets all the calls that were made to CreateSecret.
// Check the length with:
//
//	len(mockedSecretsManagerClient.CreateSecretCalls())
func (mock *SecretsManagerClientMock) CreateSecretCalls() []struct {
	Ctx    context.Context
	Params *secretsmanager.CreateSecretInput
	OptFns []func(*secretsmanager.Options)
} {
	var calls []struct {
		Ctx    context.Context
		Params *secretsmanager.CreateSecretInput
		OptFns []func(*secretsmanager.Options)
	}
	mock.lockCreateSecret.RLock()
	calls = mock.calls.CreateSecret
	mock.lockCreateSecret.RUnlock()
	return calls
}

// GetSecretValue calls GetSecretValueFunc.
func (mock *SecretsManagerClientMock) GetSecretValue(ctx context.Context, params *secretsmanager.GetSecretValueInput, optFns ...func(*secretsmanager.Options)) (*secretsmanager.GetSecretValueOutput, error) {
	if mock.GetSecretValueFunc == nil {
		panic("SecretsManagerClientMock.GetSecretValueFunc: method is nil but SecretsManagerClient.GetSecretValue was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params *secretsmanager.GetSecretValueInput
		OptFns []func(*secretsmanager.Options)
	}{
		Ctx:    ctx,
		Params: params,
		OptFns: optFns,
	}
	mock.lockGetSecretValue.Lock()
	mock.calls.GetSecretValue = append(mock.calls.GetSecretValue, callInfo)
	mock.lockGetSecretValue.Unlock()
	return mock.GetSecretValueFunc(ctx, params, optFns...)
}

// GetSecretValueCalls gets all the calls that were made to GetSecretValue.
// Check the length with:
//
//	len(mockedSecretsManagerClient.GetSecretValueCalls())
func (mock *SecretsManagerClientMock) GetSecretValueCalls() []struct {
	Ctx    context.Context
	Params *secretsmanager.GetSecretValueInput
	OptFns []func(*secretsmanager.Options)
} {
	var calls []struct {
		Ctx    context.Context
		Params *secretsmanager.GetSecretValueInput
		OptFns []func(*secretsmanager.Options)
	}
	mock.lockGetSecretValue.RLock()
	calls = mock.calls.GetSecretValue
	mock.lockGetSecretValue.RUnlock()
	return calls
}

// PutSecretValue calls PutSecretValueFunc.
func (mock *SecretsManagerClientMock) PutSecretValue(ctx context.Context, params *secretsmanager.PutSecretValueInput, optFns ...func(*secretsmanager.Options)) (*secretsmanager.PutSecretValueOutput, error) {
	if mock.PutSecretValueFunc == nil {
		panic("SecretsManagerClientMock.PutSecretValueFunc: method is nil but SecretsManagerClient.PutSecretValue was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params *secretsmanager.PutSecretValueInput
		OptFns []func(*secretsmanager.Options)
	}{
		Ctx:    ctx,
		Params: params,
		OptFns: optFns,
	}
	mock.lockPutSecretValue.Lock()
	mock.calls.PutSecretValue = append(mock.calls.PutSecretValue, callInfo)
	mock.lockPutSecretValue.Unlock()
	return mock.PutSecretValueFunc(ctx, params, optFns...)
}

// PutSecretValueCalls gets all the calls that were made to PutSecretValue.
// Check the length with:
//
//	len(mockedSecretsManagerClient.PutSecretValueCalls())
func (mock *SecretsManagerClientMock) PutSecretValueCalls() []struct {
	Ctx    context.Context
	Params *secretsmanager.PutSecretValueInput
	OptFns []func(*secretsmanager.Options)
} {
	var calls []struct {
		Ctx    context.Context
		Params *secretsmanager.PutSecretValueInput
		OptFns []func(*secretsmanager.Options)
	}
	mock.lockPutSecretValue.RLock()
	calls = mock.calls.PutSecretValue
	mock.lockPutSecretValue.RUnlock()
	return calls
}
