name: Discovery
description: Discovers Earthfiles
inputs:
  absolute:
    description: Output absolute paths
    default: "false"
  filters:
    description: A newline separated list of filters to apply
    default: ""
  path:
    description: The path to search from
    default: "."
outputs:
  deployments:
    description: The deployments discovered
  earthfiles:
    description: The earthfiles discovered

runs:
  using: node20
  main: dist/index.js
