name: Setup CI
description: Sets up the CI with the configured providers
inputs:
  github_token:
    description: Github token assigned to CI
    required: false
    default: ${{ github.token }}
  skip_aws:
    description: If true, skip authenticating with AWS and configuring ECR
    required: false
    default: "false"
  skip_cue:
    description: If true, skips installing CUE CLI if the provider is configured
    required: false
    default: "false"
  skip_docker:
    description: If true, skip authenticating to DockerHub
    required: false
    default: "false"
  skip_earthly:
    description: If true, skip installing Earthly and authenticating to Earthly Cloud
    required: false
    default: "false"
  skip_github:
    description: If true, skip authenticating to GitHub Container Registry
    required: false
    default: "false"
  skip_kcl:
    description: If true, skips installing KCL CLI if the provider is configured
    required: false
    default: "false"
  skip_timoni:
    description: If true, skips installing Timoni CLI if the provider is configured
    required: false
    default: "false"

runs:
  using: composite
  steps:
    # AWS Provider
    - name: Get AWS provider configuration
      id: aws
      if: inputs.skip_aws  == 'false'
      #continue-on-error: true
      shell: bash
      run: |
        echo "==== AWS Setup ====="
        BP=$(forge dump .)

        AWS=$(echo "$BP" | jq -r .global.ci.providers.aws)
        if [[ "$AWS" != "null" ]]; then
          REGION=$(echo "$BP" | jq -r .global.ci.providers.aws.region)
          REGISTRY=$(echo "$BP" | jq -r .global.ci.providers.aws.ecr.registry)
          ROLE=$(echo "$BP" | jq -r .global.ci.providers.aws.role)

          echo "region=$REGION" >> $GITHUB_OUTPUT
          echo "registry=$REGISTRY" >> $GITHUB_OUTPUT
          echo "role=$ROLE" >> $GITHUB_OUTPUT
        else
          echo "No configuration found for AWS provider"
        fi
    - name: Login to AWS
      uses: aws-actions/configure-aws-credentials@v4
      if: steps.aws.outputs.region  != '' && steps.aws.outputs.role != '' && steps.aws.conclusion == 'success'
      with:
        aws-region: ${{ steps.aws.outputs.region }}
        role-to-assume: ${{ steps.aws.outputs.role }}
    - name: Login to ECR
      uses: docker/login-action@v3
      if: steps.aws.outputs.registry != 'null' && steps.aws.conclusion == 'success'
      with:
        registry: ${{ steps.aws.outputs.registry }}

    # Docker Provider
    - name: Get Docker provider configuration
      id: docker
      if: inputs.skip_docker  == 'false'
      #continue-on-error: true
      shell: bash
      run: |
        echo "==== Docker Setup ====="
        BP=$(forge dump .)

        DOCKER=$(echo "$BP" | jq -r .global.ci.providers.docker.credentials)
        if [[ "$DOCKER" != "null" ]]; then
          SECRET=$(forge secret get --project . global.ci.providers.docker.credentials)
          USERNAME=$(echo "$SECRET" | jq -r .username)
          PASSWORD=$(echo "$SECRET" | jq -r .password)

          if [[ "$USERNAME" == "null" || "$PASSWORD" == "null" ]]; then
            echo "Error: the docker provider secret must map secret values to 'username' and 'password'"
            exit 1
          fi

          echo "::add-mask::$USERNAME"
          echo "::add-mask::$PASSWORD"

          echo "username=$USERNAME" >> $GITHUB_OUTPUT
          echo "password=$PASSWORD" >> $GITHUB_OUTPUT
        else
          echo "No configuration found for DockerHub provider"
        fi
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      if: steps.docker.outputs.username != '' && steps.docker.outputs.password != '' && steps.docker.conclusion == 'success'
      with:
        username: ${{ steps.docker.outputs.username }}
        password: ${{ steps.docker.outputs.password }}

    # GitHub Provider
    - name: Get GitHub provider configuration
      id: github
      if: inputs.skip_github  == 'false'
      shell: bash
      run: |
        echo "==== GitHub Setup ====="
        BP=$(forge dump .)

        GITHUB=$(echo "$BP" | jq -r .global.ci.providers.github.registry)
        if [[ "$GITHUB" != "null" ]]; then
          LOGIN=1
          echo "login=$LOGIN" >> $GITHUB_OUTPUT
        else
          echo "No configuration found for GitHub provider"
        fi
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      if: steps.github.outputs.login && steps.github.conclusion == 'success'
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    # Earthly Provider
    - name: Get Earthly provider configuration
      if: inputs.skip_earthly == 'false'
      id: earthly
      shell: bash
      run: |
        echo "==== Earthly Setup ====="
        BP=$(forge dump .)

        VERSION="latest"

        EARTHLY=$(echo "$BP" | jq -r .global.ci.providers.earthly)
        if [[ "$EARTHLY" != "null" ]]; then
          VERSION=$(echo "$BP" | jq -r .global.ci.providers.earthly.version)

          SATELLITE_CREDS=$(echo "$BP" | jq -r .global.ci.providers.earthly.satellite.creds)
          if [[ "$SATELLITE_CREDS" != "null" ]]; then
            CONFIG_SAT="true"
          else
            CONFIG_SAT="false"
            echo "No configuration found for remote Earthly satellite"
          fi
        else
          echo "No configuration found for Earthly provider"
        fi

        echo "sat=$CONFIG_SAT" >> GITHUB_OUTPUT
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    - name: Cache Earthly binary
      id: cache-binary
      uses: actions/cache@v4
      if: inputs.skip_earthly == 'false'
      with:
        path: /usr/local/bin/earthly
        key: ${{ runner.os }}-${{ steps.earthly.outputs.version }}
    - name: Install Earthly
      if: inputs.skip_earthly == 'false' && steps.cache-binary.outputs.cache-hit == false
      shell: bash
      run: |
        if [[ "${{ steps.earthly.outputs.version }}" == "latest" ]]; then
          wget -q https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly
        else
          wget -q https://github.com/earthly/earthly/releases/download/v${{ steps.earthly.outputs.version}}/earthly-linux-amd64 -O /usr/local/bin/earthly
        fi

        chmod +x /usr/local/bin/earthly
        /usr/local/bin/earthly bootstrap
    - name: Configure Earthly satellite credentials
      if: inputs.skip_earthly == 'false' && steps.earthly.outputs.sat == 'true' && steps.earthly.conclusion == 'success'
      shell: bash
      run: |
        forge configure-satellite -vvv --ci

    # Timoni Provider
    - name: Get Timoni provider configuration
      id: timoni
      if: inputs.skip_timoni  == 'false'
      shell: bash
      run: |
        echo "==== Timoni Setup ====="
        BP=$(forge dump .)

        TIMONI=$(echo "$BP" | jq -r .global.ci.providers.timoni.install)
        if [[ "$TIMONI" == "true" ]]; then
          INSTALL=1
          VERSION=$(echo "$BP" | jq -r .global.ci.providers.timoni.version)
          echo "install=$INSTALL" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        else
          echo "Not installing Timoni CLI"
        fi
    - name: Install Timoni
      uses: stefanprodan/timoni/actions/setup@main
      if: steps.timoni.outputs.install && steps.timoni.conclusion == 'success'
      with:
        version: ${{ steps.timoni.outputs.version }}

    # CUE Provider
    - name: Get CUE provider configuration
      id: cue
      if: inputs.skip_cue  == 'false'
      shell: bash
      run: |
        echo "==== CUE Setup ====="
        BP=$(forge dump .)

        CUE=$(echo "$BP" | jq -r .global.ci.providers.cue.install)
        if [[ "$CUE" == "true" ]]; then
          INSTALL=1
          VERSION=$(echo "$BP" | jq -r .global.ci.providers.cue.version)
          echo "install=$INSTALL" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        else
          echo "Not installing CUE CLI"
        fi
    - name: Install CUE
      uses: cue-lang/setup-cue@v1.0.0
      if: steps.cue.outputs.install && steps.cue.conclusion == 'success'
      with:
        version: v${{ steps.cue.outputs.version }}

    # KCL Provider
    - name: Get KCL provider configuration
      id: kcl
      if: inputs.skip_kcl  == 'false'
      shell: bash
      run: |
        echo "==== KCL Setup ====="
        BP=$(forge dump .)

        KCL=$(echo "$BP" | jq -r .global.ci.providers.kcl.install)
        if [[ "$KCL" == "true" ]]; then
          INSTALL=1
          VERSION=$(echo "$BP" | jq -r .global.ci.providers.kcl.version)
          echo "install=$INSTALL" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        else
          echo "Not installing KCL CLI"
        fi
    - name: Cache KCL
      id: cache-kcl
      if: steps.kcl.outputs.install && steps.kcl.conclusion == 'success'
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/kcl
        key: ${{ runner.os }}-kcl-${{ steps.kcl.outputs.version }}
    - name: Install KCL
      if: steps.kcl.outputs.install && steps.cache-kcl.outputs.cache-hit == false
      shell: bash
      run: |
        WORKDIR="$(mktemp -d)"
        VERSION="${{ steps.kcl.outputs.version }}"
        curl -Lo "${WORKDIR}/kcl.tar.gz" https://github.com/kcl-lang/cli/releases/download/$VERSION/kcl-$VERSION-linux-amd64.tar.gz
        cd "${WORKDIR}" && tar -xvzf kcl.tar.gz && mv kcl /usr/local/bin/kcl
    - name: Check KCL
      if: steps.kcl.outputs.install && steps.kcl.conclusion == 'success'
      shell: bash
      run: |
        kcl version
