// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/input-output-hk/catalyst-forge/lib/foundry/client/auth"
	"sync"
)

// Ensure, that AuthClientInterfaceMock does implement auth.AuthClientInterface.
// If this is not the case, regenerate this file with moq.
var _ auth.AuthClientInterface = &AuthClientInterfaceMock{}

// AuthClientInterfaceMock is a mock implementation of auth.AuthClientInterface.
//
//	func TestSomethingThatUsesAuthClientInterface(t *testing.T) {
//
//		// make and configure a mocked auth.AuthClientInterface
//		mockedAuthClientInterface := &AuthClientInterfaceMock{
//			CreateChallengeFunc: func(ctx context.Context, req *auth.ChallengeRequest) (*auth.ChallengeResponse, error) {
//				panic("mock out the CreateChallenge method")
//			},
//			LoginFunc: func(ctx context.Context, req *auth.LoginRequest) (*auth.LoginResponse, error) {
//				panic("mock out the Login method")
//			},
//		}
//
//		// use mockedAuthClientInterface in code that requires auth.AuthClientInterface
//		// and then make assertions.
//
//	}
type AuthClientInterfaceMock struct {
	// CreateChallengeFunc mocks the CreateChallenge method.
	CreateChallengeFunc func(ctx context.Context, req *auth.ChallengeRequest) (*auth.ChallengeResponse, error)

	// LoginFunc mocks the Login method.
	LoginFunc func(ctx context.Context, req *auth.LoginRequest) (*auth.LoginResponse, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateChallenge holds details about calls to the CreateChallenge method.
		CreateChallenge []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *auth.ChallengeRequest
		}
		// Login holds details about calls to the Login method.
		Login []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *auth.LoginRequest
		}
	}
	lockCreateChallenge sync.RWMutex
	lockLogin           sync.RWMutex
}

// CreateChallenge calls CreateChallengeFunc.
func (mock *AuthClientInterfaceMock) CreateChallenge(ctx context.Context, req *auth.ChallengeRequest) (*auth.ChallengeResponse, error) {
	if mock.CreateChallengeFunc == nil {
		panic("AuthClientInterfaceMock.CreateChallengeFunc: method is nil but AuthClientInterface.CreateChallenge was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *auth.ChallengeRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockCreateChallenge.Lock()
	mock.calls.CreateChallenge = append(mock.calls.CreateChallenge, callInfo)
	mock.lockCreateChallenge.Unlock()
	return mock.CreateChallengeFunc(ctx, req)
}

// CreateChallengeCalls gets all the calls that were made to CreateChallenge.
// Check the length with:
//
//	len(mockedAuthClientInterface.CreateChallengeCalls())
func (mock *AuthClientInterfaceMock) CreateChallengeCalls() []struct {
	Ctx context.Context
	Req *auth.ChallengeRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *auth.ChallengeRequest
	}
	mock.lockCreateChallenge.RLock()
	calls = mock.calls.CreateChallenge
	mock.lockCreateChallenge.RUnlock()
	return calls
}

// Login calls LoginFunc.
func (mock *AuthClientInterfaceMock) Login(ctx context.Context, req *auth.LoginRequest) (*auth.LoginResponse, error) {
	if mock.LoginFunc == nil {
		panic("AuthClientInterfaceMock.LoginFunc: method is nil but AuthClientInterface.Login was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *auth.LoginRequest
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockLogin.Lock()
	mock.calls.Login = append(mock.calls.Login, callInfo)
	mock.lockLogin.Unlock()
	return mock.LoginFunc(ctx, req)
}

// LoginCalls gets all the calls that were made to Login.
// Check the length with:
//
//	len(mockedAuthClientInterface.LoginCalls())
func (mock *AuthClientInterfaceMock) LoginCalls() []struct {
	Ctx context.Context
	Req *auth.LoginRequest
} {
	var calls []struct {
		Ctx context.Context
		Req *auth.LoginRequest
	}
	mock.lockLogin.RLock()
	calls = mock.calls.Login
	mock.lockLogin.RUnlock()
	return calls
}
