VERSION 0.8

uv:
    FROM ghcr.io/astral-sh/uv:0.4.12

    SAVE ARTIFACT /uv uv

deps:
    FROM python:3.12-slim-bookworm

    ENV UV_COMPILE_BYTECODE=0

    WORKDIR /work

    COPY +uv/uv /usr/local/bin/uv
    COPY pyproject.toml uv.lock .

    RUN uv sync --frozen --no-install-project

src:
    FROM +deps

    COPY --dir src mkdocs.yml .

build:
    FROM +src

    RUN uv run mkdocs build --strict --site-dir dist

    SAVE ARTIFACT dist

docs:
    FROM +build

    SAVE ARTIFACT dist/* .