site_name: Catalyst Forge
site_url: https://input-output-hk.github.io/catalyst-forge
site_author: The Project Catalyst Team
copyright: © 2024 Input Output Global Ltd.

docs_dir: src

theme:
  name: material
  icon:
    logo: material/anvil
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: blue grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.tooltips
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences