[project]
name = "docs"
version = "0.1.0"
description = "Catalyst Forge documentation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mkdocs-material[imaging]>=9.5.34",
    "mkdocs-panzoom-plugin>=0.3.0",
]

[tool.uv]
dev-dependencies = []
