name: Install Forge CLI
description: Installs the Catalyst Forge CLI on the local runner
inputs:
  earthly_version:
    description: The version of Earthly to install if not present
    default: "latest"
runs:
  using: composite
  steps:
    - name: Check if earthly is installed
      continue-on-error: true
      id: check
      shell: bash
      run: |
        if ! command -v earthly &> /dev/null; then
          echo "found=false" >> $GITHUB_OUTPUT
        else
          echo "found=true" >> $GITHUB_OUTPUT
        fi
    - name: Install Earthly
      uses: earthly/actions-setup@v1
      if: steps.check.outputs.found == 'false'
      with:
        version: ${{ inputs.earthly_version }}
    - name: Cache Forge CLI binary
      id: cache-forge
      uses: actions/cache@v3
      with:
        path: /usr/local/bin/forge
        key: ${{ runner.os }}-forge-${{ hashFiles('forge/cli/**') }}
        restore-keys: |
          ${{ runner.os }}-forge-
    - name: Build Forge CLI
      if: steps.cache-forge.outputs.cache-hit != 'true'
      shell: bash
      run: |
          earthly --artifact ./forge/cli+build/forge /usr/local/bin/forge
    - name: Check version
      shell: bash
      run: forge version
