on:
  workflow_call:
    inputs:
      forge_version:
        description: |
          The version of the forge CLI to install (use 'local' for testing)
        type: string
        required: false
        default: latest
    secrets:
      earthly_token:
        description: Optional Earthly token used to login to Earthly cloud during local builds of Forge CLI
        required: false

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.discovery.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - name: Test
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -L "https://github.com/input-output-hk/catalyst-forge/releases/download/forge/v0.1.0/forge-linux-amd64.tar.gz" -O
          ls -la forge-linux-amd64.tar.gz
      - name: Install Forge
        uses: ./forge/actions/install
        with:
          earthly_token: ${{ secrets.earthly_token }}
          version: ${{ inputs.forge_version }}
      - id: local
        run: |
          if [[ "${{ inputs.forge_version }}" == "local" ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi
      - name: Setup CI
        uses: ./forge/actions/setup
        with:
          skip_earthly: ${{ steps.local.outputs.skip }}
      - name: Discovery
        id: discovery
        uses: ./forge/actions/discovery
        with:
          filters: |
            ^build.*
            ^check.*
            ^test.*
            publish
            release

  check:
    uses: ./.github/workflows/run.yml
    needs: [discover]
    with:
      earthfiles: ${{ toJson(fromJson(needs.discover.outputs.result)['^check.*']) }}
      forge_version: ${{ inputs.forge_version }}
    secrets:
      earthly_token: ${{ secrets.earthly_token }}

  build:
    uses: ./.github/workflows/run.yml
    needs: [discover, check]
    with:
      earthfiles: ${{ toJson(fromJson(needs.discover.outputs.result)['^build.*']) }}
      forge_version: ${{ inputs.forge_version }}
    secrets:
      earthly_token: ${{ secrets.earthly_token }}

  test:
    uses: ./.github/workflows/run.yml
    needs: [discover, check, build]
    with:
      earthfiles: ${{ toJson(fromJson(needs.discover.outputs.result)['^test.*']) }}
      forge_version: ${{ inputs.forge_version }}
    secrets:
      earthly_token: ${{ secrets.earthly_token }}

  publish:
    uses: ./.github/workflows/publish.yml
    needs: [discover, check, build, test]
    with:
      earthfiles: ${{ toJson(fromJson(needs.discover.outputs.result)['publish']) }}
      forge_version: ${{ inputs.forge_version }}
    secrets:
      earthly_token: ${{ secrets.earthly_token }}

  release:
    uses: ./.github/workflows/release.yml
    needs: [discover, check, build, test]
    with:
      earthfiles: ${{ toJson(fromJson(needs.discover.outputs.result)['release']) }}
      forge_version: ${{ inputs.forge_version }}
    secrets:
      earthly_token: ${{ secrets.earthly_token }}