on:
  workflow_call:
    inputs:
      forge_version:
        description: |
          The version of the forge CLI to install (use 'local' for testing)
        required: true
        type: string
    secrets:
      earthly_token:
        description: Optional Earthly token used to login to Earthly cloud during local builds of Forge CLI
        required: false

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.discovery.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./forge/actions/setup
        with:
          earthly_token: ${{ secrets.earthly_token }}
          forge_version: ${{ inputs.forge_version }}
      - name: Discovery
        id: discovery
        uses: ./forge/actions/discovery
        with:
          filters: |
            ^build.*
            ^check.*
            ^test.*
            publish
            release

  # check:
  #   uses: ./.github/workflows/run.yml
  #   needs: [discover]
  #   with:
  #     earthfiles: ${{ toJson(fromJson(needs.discover.outputs.result)['^check.*']) }}
  #     forge_version: ${{ inputs.forge_version }}
  #   secrets:
  #     earthly_token: ${{ secrets.earthly_token }}

  # build:
  #   uses: ./.github/workflows/run.yml
  #   needs: [discover, check]
  #   with:
  #     earthfiles: ${{ toJson(fromJson(needs.discover.outputs.result)['^build.*']) }}
  #     forge_version: ${{ inputs.forge_version }}
  #   secrets:
  #     earthly_token: ${{ secrets.earthly_token }}

  # test:
  #   uses: ./.github/workflows/run.yml
  #   needs: [discover, check, build]
  #   with:
  #     earthfiles: ${{ toJson(fromJson(needs.discover.outputs.result)['^test.*']) }}
  #     forge_version: ${{ inputs.forge_version }}
  #   secrets:
  #     earthly_token: ${{ secrets.earthly_token }}

  # publish:
  #   uses: ./.github/workflows/publish.yml
  #   needs: [discover, check, build, test]
  #   with:
  #     earthfiles: ${{ toJson(fromJson(needs.discover.outputs.result)['publish']) }}
  #     forge_version: ${{ inputs.forge_version }}
  #   secrets:
  #     earthly_token: ${{ secrets.earthly_token }}

  release:
    uses: ./.github/workflows/release.yml
    #needs: [discover, check, build, test]
    needs: [discover]
    with:
      earthfiles: ${{ toJson(fromJson(needs.discover.outputs.result)['release']) }}
      forge_version: ${{ inputs.forge_version }}
    secrets:
      earthly_token: ${{ secrets.earthly_token }}