on:
  workflow_call:
    inputs:
      forge_version:
        description: |
          The version of the forge CLI to install (use 'local' for testing)
        type: string
        required: false
        default: latest
      local:
        description: Forces local mode
        required: false
        type: string
        default: "false"
      release_only:
        description: Only run the release job
        required: false
        type: boolean
        default: false
      verbosity:
        description: The verbosity level to use
        required: false
        type: string
        default: "info"
      nightly:
        description: Runs nightly targets
        required: false
        type: boolean
        default: false

env:
  FORGE_REGEX_CHECK: ^check(-.*)?$
  FORGE_REGEX_BUILD: ^build(-.*)?$
  FORGE_REGEX_PACKAGE: ^package(-.*)?$
  FORGE_REGEX_TEST: ^test(-.*)?$
  FORGE_REGEX_DOCS: ^docs(-.*)?$
  FORGE_REGEX_RELEASE: ^release(-.*)?$
  FORGE_REGEX_PUBLISH: ^publish(-.*)?$
  FORGE_REGEX_NIGHTLY: ^nightly(-.*)?$

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      deployments: ${{ steps.discovery.outputs.deployments }}
      earthfiles: ${{ steps.discovery.outputs.earthfiles }}
      releases: ${{ steps.discovery.outputs.releases }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Forge
        uses: input-output-hk/catalyst-forge/actions/install@master
        if: ${{ inputs.forge_version != 'local' }}
        with:
          enable_caching: "true"
          version: ${{ inputs.forge_version }}
      - name: Install Local Forge
        id: install-local
        uses: input-output-hk/catalyst-forge/actions/install-local@master
        if: ${{ inputs.forge_version == 'local' }}
      - name: Check forge version
        id: local
        run: |
          forge version
      - name: Setup CI
        uses: input-output-hk/catalyst-forge/actions/setup@master
        with:
          skip_docker: 'true'
          skip_github: 'true'
          skip_earthly_install: ${{ inputs.forge_version == 'local' && steps.install-local.outputs.cache-hit == false }}
          skip_earthly_satellite: ${{ inputs.forge_version == 'local' && steps.install-local.outputs.cache-hit == false }}
      - name: Discovery
        id: discovery
        uses: input-output-hk/catalyst-forge/actions/discovery@master
        with:
          filters: |
            ${{ env.FORGE_REGEX_CHECK }}
            ${{ env.FORGE_REGEX_BUILD }}
            ${{ env.FORGE_REGEX_PACKAGE }}
            ${{ env.FORGE_REGEX_TEST }}
            ${{ env.FORGE_REGEX_DOCS }}
            ${{ env.FORGE_REGEX_RELEASE }}
            ${{ env.FORGE_REGEX_PUBLISH }}
            ${{ env.FORGE_REGEX_NIGHTLY }}
  check:
    uses: input-output-hk/catalyst-forge/.github/workflows/run.yml@master
    needs: [discover]
    if: (fromJson(needs.discover.outputs.earthfiles)['^check(-.*)?$'] != null) && (inputs.release_only == false) && !failure() && !cancelled()
    with:
      earthfiles: ${{ toJson(fromJson(needs.discover.outputs.earthfiles)['^check(-.*)?$']) }}
      forge_version: ${{ inputs.forge_version }}
      local: ${{ inputs.local }}
      skip_output: true
      verbosity: ${{ inputs.verbosity }}

  build:
    uses: input-output-hk/catalyst-forge/.github/workflows/run.yml@master
    needs: [discover, check]
    if: (fromJson(needs.discover.outputs.earthfiles)['^build(-.*)?$'] != null) && (inputs.release_only == false) && !failure() && !cancelled()
    with:
      earthfiles: ${{ toJson(fromJson(needs.discover.outputs.earthfiles)['^build(-.*)?$']) }}
      forge_version: ${{ inputs.forge_version }}
      local: ${{ inputs.local }}
      skip_output: true
      verbosity: ${{ inputs.verbosity }}

  package:
    uses: input-output-hk/catalyst-forge/.github/workflows/run.yml@master
    needs: [discover, check, build]
    if: (fromJson(needs.discover.outputs.earthfiles)['^package(-.*)?$'] != null) && (inputs.release_only == false) && !failure() && !cancelled()
    with:
      earthfiles: ${{ toJson(fromJson(needs.discover.outputs.earthfiles)['^package(-.*)?$']) }}
      forge_version: ${{ inputs.forge_version }}
      local: ${{ inputs.local }}
      skip_output: true
      verbosity: ${{ inputs.verbosity }}

  test:
    uses: input-output-hk/catalyst-forge/.github/workflows/run.yml@master
    needs: [discover, check, build, package]
    if: (fromJson(needs.discover.outputs.earthfiles)['^test(-.*)?$'] != null) && (inputs.release_only == false) && !failure() && !cancelled()
    with:
      earthfiles: ${{ toJson(fromJson(needs.discover.outputs.earthfiles)['^test(-.*)?$']) }}
      forge_version: ${{ inputs.forge_version }}
      local: ${{ inputs.local }}
      skip_output: true
      verbosity: ${{ inputs.verbosity }}

  nightly:
    uses: input-output-hk/catalyst-forge/.github/workflows/run.yml@master
    needs: [discover, check, build, package]
    if: (fromJson(needs.discover.outputs.earthfiles)['^nightly(-.*)?$'] != null) && (inputs.release_only == false) && !failure() && !cancelled() && inputs.nightly == true
    with:
      earthfiles: ${{ toJson(fromJson(needs.discover.outputs.earthfiles)['^nightly(-.*)?$']) }}
      forge_version: ${{ inputs.forge_version }}
      local: ${{ inputs.local }}
      skip_output: true
      verbosity: ${{ inputs.verbosity }}

  release:
    uses: input-output-hk/catalyst-forge/.github/workflows/release.yml@master
    needs: [discover, check, build, test]
    if: (fromJson(needs.discover.outputs.releases)[0] != null) && !failure() && !cancelled()
    with:
      releases: ${{ needs.discover.outputs.releases }}
      forge_version: ${{ inputs.forge_version }}
      local: ${{ inputs.local }}
      verbosity: ${{ inputs.verbosity }}

  deploy:
    uses: input-output-hk/catalyst-forge/.github/workflows/deploy.yml@master
    needs: [discover, check, build, test, release]
    if: (fromJson(needs.discover.outputs.deployments)[0] != null) && !failure() && !cancelled()
    with:
      deployments: ${{ needs.discover.outputs.deployments }}
      forge_version: ${{ inputs.forge_version }}
      local: ${{ inputs.local }}
      verbosity: ${{ inputs.verbosity }}

  final:
    needs: [check, build, package, test, nightly, release, deploy]
    if: ${{ always() && (contains(needs.*.result, 'failure') || !failure() && !cancelled()) }}
    runs-on: ubuntu-latest
    steps:
      - name: Final
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]
          then
            echo "Run failed"
            exit 1
          else
            echo "All done"
          fi