on:
  workflow_call:
    inputs:
      deployments:
        description: |
          The deployments to be executed
        required: true
        type: string
      forge_version:
        description: |
          The version of the forge CLI to install (use 'local' for testing)
        required: true
        type: string
      local:
        description: Forces local mode
        required: false
        type: string
        default: "false"
      verbosity:
        description: The verbosity level to use
        required: false
        type: string
        default: "info"

env:
  CONTAINER: container
  TAG: tag

jobs:
  run:
    name: ${{ matrix.deployment }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        deployment: ${{ fromJson(inputs.deployments) }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Forge
        uses: input-output-hk/catalyst-forge/actions/install@ci/v1.9.0
        if: ${{ inputs.forge_version != 'local' }}
        with:
          version: ${{ inputs.forge_version }}
      - name: Install Local Forge
        uses: input-output-hk/catalyst-forge/actions/install-local@ci/v1.9.0
        id: install-local
        if: ${{ inputs.forge_version == 'local' }}
      - name: Check forge version
        run: forge version
      - name: Setup CI
        uses: input-output-hk/catalyst-forge/actions/setup@ci/v1.9.0
        with:
          skip_earthly_install: ${{ inputs.forge_version == 'local' && steps.install-local.outputs.cache-hit == false }}
          skip_earthly_satellite: ${{ inputs.forge_version == 'local' && steps.install-local.outputs.cache-hit == false }}
      - name: Deploy
        uses: input-output-hk/catalyst-forge/actions/run@ci/v1.9.0
        with:
          command: mod deploy
          args: ${{ matrix.deployment }}
          local: ${{ inputs.local }}
          verbosity: ${{ inputs.verbosity }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}