name: Dogfood

on:
  push:

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      forge_version: 0.1.0
    secrets:
      earthly_token: ${{ secrets.EARTHLY_TOKEN }}