on:
  workflow_call:
    inputs:
      earthfiles:
        description: |
          A JSON list of Earthfile paths+targets to use for publishing
        required: true
        type: string
      forge_version:
        description: |
          The version of the forge CLI to install (use 'local' for testing)
        required: true
        type: string
    secrets:
      earthly_token:
        description: Optional Earthly token used to login to Earthly cloud during local builds of Forge CLI
        required: false

env:
  CONTAINER: container
  TAG: tag

jobs:
  run:
    name: ${{ matrix.earthfile }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        earthfile: ${{ fromJson(inputs.earthfiles) }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup CI
        uses: ./forge/actions/setup
        with:
          earthly_token: ${{ secrets.earthly_token }}
          forge_version: ${{ inputs.forge_version }}
      - name: Parse Earthfile reference
        id: parse
        run: |
          PROJECT="${EARTHFILE%+*}"
          TARGET="${EARTHFILE#*+}"

          echo "project=$PROJECT" >> $GITHUB_OUTPUT
          echo "target=$TARGET" >> $GITHUB_OUTPUT
      - name: Run
        id: run
        uses: ./forge/actions/run
        with:
          args: --container ${{ env.CONTAINER }} --tag ${{ env.TAG }}
          path: ${{ matrix.earthfile }}
      - name: Publish
        uses: ./forge/actions/publish
        with:
          image: "${{ env.CONTAINER }}:${{ env.TAG }}"
          project: ${{ steps.parse.outputs.project }}