on:
  workflow_call:
    inputs:
      releases:
        description: |
          A JSON list of releases to run
        required: true
        type: string
      force:
        description: |
          Force the release to run even if no events are triggered
        required: false
        type: string
        default: "false"
      forge_version:
        description: |
          The version of the forge CLI to install (use 'local' for testing)
        required: true
        type: string
      local:
        description: Forces local mode
        required: false
        type: string
        default: "false"
      verbosity:
        description: The verbosity level to use
        required: false
        type: string
        default: "info"
    secrets:
      earthly_token:
        description: Optional Earthly token used to login to Earthly cloud during local builds of Forge CLI
        required: false
env:
  OUTPUT: ${{ github.workspace }}/output

jobs:
  run:
    name: ${{ matrix.release.project }} (${{ matrix.release.name}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release: ${{ fromJson(inputs.releases) }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Forge
        uses: input-output-hk/catalyst-forge/actions/install@mve
        if: ${{ inputs.forge_version != 'local' }}
        with:
          version: ${{ inputs.forge_version }}
      - name: Install Local Forge
        uses: input-output-hk/catalyst-forge/actions/install-local@mve
        if: ${{ inputs.forge_version == 'local' }}
        with:
          earthly_token: ${{ secrets.earthly_token }}
      - name: Check forge version
        id: local
        run: |
          forge version

          if [[ "${{ inputs.forge_version }}" == "local" ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi
      - name: Setup CI
        uses: input-output-hk/catalyst-forge/actions/setup@mve
        with:
          skip_earthly: ${{ steps.local.outputs.skip }}
      - name: test
        run: |
          echo "$GITHUB_EVENT_PATH"
          cat "$GITHUB_EVENT_PATH"
      # - name: Release
      #   uses: input-output-hk/catalyst-forge/actions/run@mve
      #   with:
      #     command: release
      #     args: ${{ matrix.release.project }} ${{ matrix.release.name }}
      #     local: ${{ inputs.local }}
      #     verbosity: ${{ inputs.verbosity }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Release Temp
      #   uses: input-output-hk/catalyst-forge/actions/run@mve
      #   if: matrix.release.project == './foundry/api'
      #   with:
      #     command: release
      #     args: --force ${{ matrix.release.project }} ${{ matrix.release.name }}
      #     local: ${{ inputs.local }}
      #     verbosity: ${{ inputs.verbosity }}
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}