on:
  workflow_call:
    inputs:
      releases:
        description: |
          A JSON list of releases to run
        required: true
        type: string
      force:
        description: |
          Force the release to run even if no events are triggered
        required: false
        type: string
        default: "false"
      forge_version:
        description: |
          The version of the forge CLI to install (use 'local' for testing)
        required: true
        type: string
      local:
        description: Forces local mode
        required: false
        type: string
        default: "false"
      verbosity:
        description: The verbosity level to use
        required: false
        type: string
        default: "info"
env:
  OUTPUT: ${{ github.workspace }}/output

jobs:
  run:
    name: ${{ matrix.release.project }} (${{ matrix.release.name}})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release: ${{ fromJson(inputs.releases) }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Forge
        uses: input-output-hk/catalyst-forge/actions/install@filter-by-earthfile
        if: ${{ inputs.forge_version != 'local' }}
        with:
          version: ${{ inputs.forge_version }}
      - name: Install Local Forge
        id: install-local
        uses: input-output-hk/catalyst-forge/actions/install-local@filter-by-earthfile
        if: ${{ inputs.forge_version == 'local' }}
      - name: Check forge version
        run: forge version
      - name: Setup CI
        uses: input-output-hk/catalyst-forge/actions/setup@filter-by-earthfile
        with:
          skip_earthly_install: ${{ inputs.forge_version == 'local' && steps.install-local.outputs.cache-hit == false }}
          skip_earthly_satellite: ${{ inputs.forge_version == 'local' && steps.install-local.outputs.cache-hit == false }}
      - name: Release
        uses: input-output-hk/catalyst-forge/actions/run@filter-by-earthfile
        with:
          command: release
          args: ${{ matrix.release.project }} ${{ matrix.release.name }}
          local: ${{ inputs.local }}
          verbosity: ${{ inputs.verbosity }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}