on:
  workflow_call:
    inputs:
      earthfiles:
        description: |
          A JSON list of Earthfile paths+targets to run
        required: true
        type: string
      forge_version:
        description: |
          The version of the forge CLI to install (use 'local' for testing)
        required: true
        type: string
    secrets:
      earthly_token:
        description: Optional Earthly token used to login to Earthly cloud during local builds of Forge CLI
        required: false

jobs:
  run:
    name: ${{ matrix.earthfile }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        earthfile: ${{ fromJson(inputs.earthfiles) }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Forge
        uses: ./forge/actions/install
        if: ${{ inputs.forge_version != 'local' }}
        with:
          version: ${{ inputs.forge_version }}
      - name: Install Local Forge
        uses: ./forge/actions/install
        if: ${{ inputs.forge_version == 'local' }}
        with:
          earthly_token: ${{ secrets.earthly_token }}
      - name: Check forge version
        id: local
        run: |
          forge version

          if [[ "${{ inputs.forge_version }}" == "local" ]]; then
            echo "skip=true" >> $GITHUB_OUTPUT
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi
      - name: Setup CI
        uses: ./forge/actions/setup
        with:
          skip_earthly: ${{ steps.local.outputs.skip }}
      - name: Run
        uses: ./forge/actions/run
        with:
          path: ${{ matrix.earthfile }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}