on:
  workflow_call:
    inputs:
      earthfiles:
        description: |
          A JSON list of Earthfile paths+targets to run
        required: true
        type: string
      forge_version:
        description: |
          The version of the forge CLI to install (use 'local' for testing)
        required: true
        type: string
    secrets:
      earthly_token:
        description: Optional Earthly token used to login to Earthly cloud during local builds of Forge CLI
        required: false

jobs:
  run:
    name: ${{ matrix.earthfile }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        earthfile: ${{ fromJson(inputs.earthfiles) }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup CI
        uses: ./forge/actions/setup
        with:
          earthly_token: ${{ secrets.earthly_token }}
          forge_version: ${{ inputs.forge_version }}
      - name: Run
        uses: ./forge/actions/run
        with:
          path: ${{ matrix.earthfile }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}