on:
  workflow_call:
    inputs:
      earthfiles:
        description: |
          A JSON list of Earthfile paths+targets to run
        required: true
        type: string
      forge_version:
        description: |
          The version of the forge CLI to install (use 'local' for testing)
        required: true
        type: string
      local:
        description: Forces local mode
        required: false
        type: string
        default: "false"
      skip_output:
        description: Skip outputting any images or artifacts
        required: false
        type: string
        default: "false"
      target_args:
        description: Extra arguments to pass to the target (if command is "run")
        required: false
        type: string
        default: ""
      verbosity:
        description: The verbosity level to use
        required: false
        type: string
        default: "info"
    secrets:
      earthly_token:
        description: Optional Earthly token used to login to Earthly cloud during local builds of Forge CLI
        required: false

jobs:
  run:
    name: ${{ matrix.earthfile }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        earthfile: ${{ fromJson(inputs.earthfiles) }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Forge
        uses: input-output-hk/catalyst-forge/actions/install@ci-improvements
        if: ${{ inputs.forge_version != 'local' }}
        with:
          version: ${{ inputs.forge_version }}
      - name: Install Local Forge
        id: install-local
        uses: input-output-hk/catalyst-forge/actions/install-local@ci-improvements
        if: ${{ inputs.forge_version == 'local' }}
        with:
          earthly_token: ${{ secrets.earthly_token }}
      - name: Check forge version
        id: local
        run: |
          forge version
      - name: Setup CI
        uses: input-output-hk/catalyst-forge/actions/setup@ci-improvements
        with:
          skip_earthly_install: ${{ inputs.forge_version == 'local' && steps.install-local.outputs.cache-hit == false }}
          skip_earthly_satellite: ${{ inputs.forge_version == 'local' && steps.install-local.outputs.cache-hit == false }}
      - name: Run
        uses: input-output-hk/catalyst-forge/actions/run@ci-improvements
        with:
          command: run
          args: ${{ matrix.earthfile }}
          local: ${{ inputs.local }}
          skip_output: ${{ inputs.skip_output }}
          target_args: ${{ inputs.target_args }}
          verbosity: ${{ inputs.verbosity }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}