name: Test
on:
  push:

permissions:
  contents: read
  id-token: write

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.discovery.outputs.result }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./forge/actions/setup
        with:
          forge_version: local
      - name: Discovery
        id: discovery
        uses: ./forge/actions/discovery
        with:
          filters: |
            ^check.*
            ^test.*
  check:
    uses: ./.github/workflows/run.yml
    needs: [discover]
    with:
      earthfiles: ${{ fromJson(needs.discover.outputs.result)['^check.*'] }}
