name: Test Foundry API

on:
  push:
    branches: [master]
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  test-auth-endpoint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Local Forge
        id: install-local
        uses: input-output-hk/catalyst-forge/actions/install-local@master
      - name: Check forge version
        id: local
        run: |
          forge version

      - name: Setup CI
        uses: input-output-hk/catalyst-forge/actions/setup@master
        with:
          skip_docker: 'true'
          skip_github: 'true'

      - name: Build API image
        run: |
            forge run ./foundry/api+docker

      # - name: Build test image
      #   run: |
      #       forge run ./foundry/api+docker-test

      - name: Start API
        run: |
          docker compose -f ./foundry/api/docker-compose.yml up -d auth auth-jwt api postgres step-ca || docker compose -f ./foundry/api/docker-compose.yml logs step-ca

      - name: Wait for API to be ready
        run: |
          sleep 1

      - name: Run test
        run: |
            docker compose -f ./foundry/api/docker-compose.yml up --abort-on-container-exit --exit-code-from api-test